### ISSUE TITLE
Error "Trade volume not within limits: min: 1000000000000, max: 1000000000000000" - system doesn't allow prices < 1.0

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#10]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

System is not accepting my buy order.

![image](https://user-images.githubusercontent.com/6218678/177199445-606b04da-17ff-474b-87fc-0d82cae1e14b.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
Tried entering a buy order for 1 PDEX with price 0.9 TDOT

**Comment by jaymansfield** [comment]
Seems to happen when price < 1

**Comment by nuel77** [comment]
yea, the current market is set with a trading limit for a min of 1 unit , this is configurable. will be changed for different markets
