### ISSUE TITLE
Replace default favicon with pdex logo and add page titles

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#100]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

Replace default favicon with pdex logo and add page titles

![image](https://user-images.githubusercontent.com/6218678/177563109-34e8081c-9cf4-4b58-9323-4c33c6314abc.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment]
Already implemented in the current version. @minikas please add the pr link.
