### ISSUE TITLE
"Hide other pairs" "Buy" "Sell" doesn't work

### ISSUE THREAD

**Issue by Ste7777** [Polkadex-Substrate/Polkadex-Open-Beta#106]
Trying to Switch betwenn "Buy" or "Sell" or "Hide other pairs" Function doesn't work. Nothing happens.

**Comment by charleslukes** [comment]
works now

**Comment by pdexpab** [comment]
@Ste7777 - ACTION NEEDED 

⚠️ If the issues you've logged are tagged as 'Unconfirmed', your on-chain identity has not been set up yet. Please be sure the issues you have raised on GitHub match up to a verified on-chain identity so your issue can be counted in the overall rewards tally for cycle 1 of Polkadex Open Beta testing. 

If you don't have a verified on-chain identity, follow the steps in [this video](https://www.youtube.com/watch?v=lJh4ROo4SiM) as soon as you can. Please drop us a line here or on Discord once you've done so.

For more details, please refer to the latest message in the Open Beta channel on the Polkadex Discord server and points 3.e and 3.f in [the Polkadex Open Beta Terms & Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)
