### ISSUE TITLE
System Error when placing a bid

### ISSUE THREAD

**Issue by Ste7777** [Polkadex-Substrate/Polkadex-Open-Beta#107]
When I tried placing a bid, there appered a error message. See the picture.

**Comment by pavankanteti** [comment]
Could you enclose the picture again?

**Comment by Ste7777** [comment]
Hey,

can not send you pictures, because I get a message, that the data is too
big. Why is that? Never have had problems before sending pictures to
somebody.

Best, Stephan.

Pavan Kanteti ***@***.***> schrieb am Fr., 8. Juli 2022,
14:09:

**Comment by Ste7777** [comment]
Pavan Kanteti ***@***.***> schrieb am Fr., 8. Juli 2022,
14:09:

**Comment by pavankanteti** [comment]
Closing as not enough data to analyze the issue.
