### ISSUE TITLE
Graph Freeze

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#113]
Clicking the graph duration (1 H, 6H, 1D, 6D) are literally freezing the UI. Consistently replicated it. See the recording.

onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}
https://user-images.githubusercontent.com/94037805/177575541-9bf77657-fb77-4cc3-93a2-cc18b1520aa8.mp4

**Comment by pavankanteti** [comment]
duplicate of #109
