### ISSUE TITLE
Add option to view the full address and detail of deposit on mouse hover

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#117]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description:
-Add option to view the full address and detail of deposit on mouse hover, it is currently cut from the view

![image](https://user-images.githubusercontent.com/108701680/177580350-2989d11c-52e9-4322-a457-5227ae02ea9c.png)

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by pavankanteti** [comment]
This is not relevant in the new implementation.
