### ISSUE TITLE
Checkmarks not working in Transactions grid.

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#120]
Checkmarks not working in Transactions grid. All 3- Buy, Sell, Hide Other Pairs- are not working and filtering data

onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}
![image](https://user-images.githubusercontent.com/94037805/177583041-bd4ac812-01ad-4a45-add6-1a55442c4a35.png)

**Comment by pavankanteti** [comment]
duplicate of #106
