### ISSUE TITLE
Deposit Freeze

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#123]
Deposit in Wallet is freezing and nothing happens when user is clicking Deposit. See recording. Sorted after refreshing and relogging.

onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}
https://user-images.githubusercontent.com/94037805/177584713-3abd5a6d-ef0f-4e7b-bf47-30af28b5fe89.mp4

**Comment by pavankanteti** [comment]
Closing as duplicate of #40
