### ISSUE TITLE
Feedback: Market Orders at least display average Price? 

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#125]
Feedback: Cant Market Orders at least display average Price? Currently Price is blank.

onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}

![image](https://user-images.githubusercontent.com/94037805/177588195-6b4c17fe-d159-47b4-8237-300058d43a48.png)

**Comment by pavankanteti** [comment]
They would close at best market price. Having any other figure would be misleading.
