### ISSUE TITLE
Limiting number of figures for prices and quoting in USD

### ISSUE THREAD

**Issue by Dude0609** [Polkadex-Substrate/Polkadex-Open-Beta#128]
Can you incorporate the prices into dollars with a comma and to four decimal places; currently there are 14 numbers so its very confusing; For example an error message came up stating 
"Error
Not enough asset free balance: available: 13406256000000, minimum required: 18000000000000"

If this could say "not enough asset free balance available: $1.3406

onchainaddress: {esoiFAMrCMufzPxBnybkhFsXWP3P5K6x4yeCEBz1q8jwSwbra}

**Comment by pavankanteti** [comment]
USD conversion will be added in the future. But balances will always show in the token amount while trading.
