### ISSUE TITLE
Users can create tokens with the same name as existing tokens -breaks orderbook deposit page

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#132]
![image](https://user-images.githubusercontent.com/6218678/177618581-55ea4973-13fa-4edf-a2cf-c46eb8905d00.png)

Created and minted a new token called TEST DOT which is the same name as the existing token. Now theres no way to see which is which on the deposit page 

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment]
You shouldn't see this in the mainnet as we will have a pipeline to list tokens on our exchange and this will be filtered there.
