### ISSUE TITLE
Dropdowns overlapping 

### ISSUE THREAD

**Issue by nashidahmed** [Polkadex-Substrate/Polkadex-Open-Beta#133]
**Description** 

Opening a button dropdown should close exisiting opened dropdowns.

**How to reproduce:**
1. Click the second last button, the wallet icon, on the top right.
2. Click the last button on the profile name button on the top right.
3. Funds dropdown appears on top of the profile dropdown.

Ex. Funds dropdown stays open even when the Profile dropdown is open causing an overlap. 

![orderbook-beta polkadex trade UI bug](https://user-images.githubusercontent.com/37153833/177720499-4371d986-fbd8-4213-89ee-2816f9fb08ce.png)

onchainaddress:{esoia6ocj8jC4Wq2mSeiCsXf1Z3eHqx7oHQ8hK8iPgHUYAmeC}

**Comment by pavankanteti** [comment]
Not applicable in the new version. Hence closing.
