### ISSUE TITLE
Order Book sorting 0.0001 to 0.1 

### ISSUE THREAD

**Issue by jcbm123143** [Polkadex-Substrate/Polkadex-Open-Beta#139]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Order Book sorting **0.0001** to **0.1** 
I try to sort **0.0001 to 0.1** but it doesn't work

![image](https://user-images.githubusercontent.com/22148449/177749353-ac39fae9-e50f-4129-b2ff-b465e2b32d27.png)

onchainaddress:{esr4zxY2vA6RqqMPppdTMEu313UDe9q8UVu8JZpZrucefyyzZ}

**Comment by pavankanteti** [comment]
closing as duplicate of #112
