### ISSUE TITLE
Bookmark not working in Market

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#14]
Clicking the 'Star'/Bookmark/Fav icon near asset pairs from Market doesn't really save anything. 

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

**Comment by pavankanteti** [comment]
Closing as duplicate
