### ISSUE TITLE
Market Order Error

### ISSUE THREAD

**Issue by jcbm123143** [Polkadex-Substrate/Polkadex-Open-Beta#141]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Market Order Error
I try to sell PDEX error message show

**Error
createType(OrderPayload):: Struct: failed on qty: u128:: String should not contain decimal points or scientific notation**

![image](https://user-images.githubusercontent.com/22148449/177751136-99c44b65-1680-4879-a3d2-e482cf800b90.png)

onchainaddress:{esr4zxY2vA6RqqMPppdTMEu313UDe9q8UVu8JZpZrucefyyzZ}

**Comment by jaymansfield** [comment]
Duplicate #83

**Comment by pavankanteti** [comment]
Closing as duplicate of #83
