### ISSUE TITLE
Limit Order Total NaN and Error

### ISSUE THREAD

**Issue by jcbm123143** [Polkadex-Substrate/Polkadex-Open-Beta#142]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

I set the order Price 10000000000000000 and the amount 1
Error message show 

**Error
createType(OrderPayload):: Struct: failed on price: u128:: String should not contain decimal points or scientific notation**

![image](https://user-images.githubusercontent.com/22148449/177753050-faba7e93-73dc-47e5-ae04-9b48e21b9fb4.png)

onchainaddress:{esr4zxY2vA6RqqMPppdTMEu313UDe9q8UVu8JZpZrucefyyzZ}

**Comment by pavankanteti** [comment]
Closing as duplicate
