### ISSUE TITLE
Funds Actions 

### ISSUE THREAD

**Issue by jcbm123143** [Polkadex-Substrate/Polkadex-Open-Beta#145]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Action - the 3 dot not working

![image](https://user-images.githubusercontent.com/22148449/177755869-b3fca036-082a-4943-9616-f4b99cbb7801.png)

onchainaddress:{esr4zxY2vA6RqqMPppdTMEu313UDe9q8UVu8JZpZrucefyyzZ}

**Comment by nuel77** [comment]
duplicated https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/96
