### ISSUE TITLE
"Application error: a client-side exception has occurred" and "Something has gone wrong (balances fetch)"

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#148]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

On orderbook page:
![image](https://user-images.githubusercontent.com/6218678/177828841-75868eed-9ac8-43df-a382-86a3a2a9e5d0.png)

On wallet page:
![image](https://user-images.githubusercontent.com/6218678/177828975-c3ff29a0-9452-41c2-b95a-32675d4ac7da.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by nuel77** [comment]
Can you also show how to replicate this?

**Comment by pavankanteti** [comment]
Closing as not enough date for reproducing the error.
