### ISSUE TITLE
Freeze when choosing 1h 6h 1d 1w time frame

### ISSUE THREAD

**Issue by TotolAstico** [Polkadex-Substrate/Polkadex-Open-Beta#156]
The orderbook page freezes when I click on one of these timeframe 1h 6h 1d 1w. And have to refresh. 

onchainaddress:{esmSs5Lx2my8DK3yk41Xfb7Gp4M13jAf5rCuLUDB3BmaJuupp}

**Comment by Darbakearg** [comment]
Same issue here.
After the freeze, the error code "Out of memory" appears.

**Comment by nuel77** [comment]
https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/85
