### ISSUE TITLE
Full screen button doesn't work 

### ISSUE THREAD

**Issue by TotolAstico** [Polkadex-Substrate/Polkadex-Open-Beta#157]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

The full screen button does't work. 

onchainaddress:{esmSs5Lx2my8DK3yk41Xfb7Gp4M13jAf5rCuLUDB3BmaJuupp}

**Comment by mastervalidator** [comment]
duplicate #114

**Comment by TotolAstico** [comment]
My bad I didn't check

**Comment by pavankanteti** [comment]
closing as duplicate of #114
