### ISSUE TITLE
UI Improvement: No Spacing between polkadex logo and token logo

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#162]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description:
-UI Improvement: No Spacing between polkadex logo and token logo

![image](https://user-images.githubusercontent.com/108701680/178102663-f2b471ef-f00f-468e-8915-90992fc40868.png)
![image](https://user-images.githubusercontent.com/108701680/178102883-9e23d105-ce51-4908-a98a-7dada28d6858.png)

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by pavankanteti** [comment]
This is by design
