### ISSUE TITLE
Having more than 4 projects in IDO Voting Breaks UI

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#167]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description:
-Having more than 4 projects in IDO Voting Breaks UI

![image](https://user-images.githubusercontent.com/108701680/178103643-cdc47d7f-2a84-492b-9439-947ef196fa2c.png)

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by pavankanteti** [comment]
The voting architecture is going to change soon for IDO.

**Comment by pavankanteti** [comment]
This issue won't be valid after that.
