### ISSUE TITLE
Deposit Page - Avlb Balance on Main Account Doesn't Get Updated After Successful Deposit

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#169]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description:
-Deposit Page - Avlb Balance on Main Account Doesn't Get Updated After Successful Deposit

https://user-images.githubusercontent.com/108701680/178104037-5b5d55d4-d2c8-4f58-b307-1823a35921e7.mp4

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by pavankanteti** [comment]
realtime updated fixed in the current version
