### ISSUE TITLE
Switch icon and Dropdown icon in Market has any use?

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#17]
Switch icon and Dropdown icon in Market has any use? Both of these icons - Swap/Switch and dropdown icon has any use case? Currently it serves no functions.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

![icons market](https://user-images.githubusercontent.com/94037805/177200924-cab37619-01cd-4d22-9afb-69e9f4f37060.png)

**Comment by DayalKS2** [comment]
It works when the left hand slider is closed. But once the left slider is opened to show the Market, then the icons dont responds

**Comment by pdexpab** [comment]
@DayalKS2 - ACTION NEEDED 

⚠️ If the issues you've logged are tagged as 'Unconfirmed', your on-chain identity has not been set up yet. Please be sure the issues you have raised on GitHub match up to a verified on-chain identity so your issue can be counted in the overall rewards tally for cycle 1 of Polkadex Open Beta testing. 

If you don't have a verified on-chain identity, follow the steps in [this video](https://www.youtube.com/watch?v=lJh4ROo4SiM) as soon as you can. Please drop us a line here or on Discord once you've done so.

For more details, please refer to the latest message in the Open Beta channel on the Polkadex Discord server and points 3.e and 3.f in [the Polkadex Open Beta Terms & Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

**Comment by DayalKS2** [comment]
Thanks for informing.  I have completed the verification process.

Regards,
Dayal

**Comment by pdexpab** [comment]
@DayalKS2 can you double check you have verified the unchain address you shared above: esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ ?

Not seeing anything for that address on the network.

**Comment by DayalKS2** [comment]
Hi,

My bad as I verified my identity in TestNet. Now I have verified my
identity in the Polkadex Mainnet for both
esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ and
espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN
which I had used to Test the application.

Let me know if you still dont see it still.

Thanks
Dayal
