### ISSUE TITLE
Deposit Button stops working if the transaction window is closed instead of cancelled

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#170]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description:
-Deposit Button stops working if the transaction window is closed instead of cancelled, even if you navigate away and get back to deposit page it still doesn't work!

https://user-images.githubusercontent.com/108701680/178104824-6cb5f745-cd4e-46cf-aa71-6ca487308e61.mp4

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by pavankanteti** [comment]
Fixed in the current version
