### ISSUE TITLE
Orderbook Breaks & Doesn't Execute Correctly if contains your own limit orders and gets filled by yourself along with other orders!

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#174]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description:
-Orderbook Breaks on both Buy/Sell Sides & Doesn't Execute Correctly if contains your own limit orders and gets filled by yourself along with other orders (cumulative) !, and also the same price will appear on both buy/sell sides (which is another bug already mentioned)!

https://user-images.githubusercontent.com/108701680/178106807-c2bf7b88-ff69-4798-bd9c-8ff80dd0e232.mp4

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by pavankanteti** [comment]
Probable cause is data corruption in database.
