### ISSUE TITLE
Arithmetic Underflow with a specially crafted custom token

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#178]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description:
-Arithmetic Underflow with a specially crafted custom token, related to xss, i can provide more information if needed..

https://user-images.githubusercontent.com/108701680/178119858-49c6ffe1-08b4-44fd-9ccd-e90d1411122a.mp4

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by jaymansfield** [comment]
#34

**Comment by mastervalidator** [comment]
> #34

funds available and still receive the error
