### ISSUE TITLE
Price is not populated

### ISSUE THREAD

**Issue by LunaPolkadex** [Polkadex-Substrate/Polkadex-Open-Beta#180]
Price is not populated

![populated](https://user-images.githubusercontent.com/109044582/178163064-06400d73-7017-45d0-8648-e6b96ddd87bf.jpg)

onchainaddress:{esnpHCUii7PvrGr5d3r2LLSseXzbKteTAsxLGHhhptmL9m4uJ}

**Comment by LunaPolkadex** [comment]
> Could you provide more context?

It happens all the time I click in Exchange. Using firefox & desktop

**Comment by pavankanteti** [comment]
Unable to reproduce. Hence closing.
