### ISSUE TITLE
Wallets tab UX / missing menu 

### ISSUE THREAD

**Issue by LunaPolkadex** [Polkadex-Substrate/Polkadex-Open-Beta#181]
Once in Wallets menu, hover over left menu and Wallets (current tab) and Markets are missing

![tab](https://user-images.githubusercontent.com/109044582/178163734-4ab5b823-a56c-4671-a3a0-80e8d1a6319a.png)

I suggest moving wallet history to My Transactions of even better create a Deposit/Withdrawals section to make it more clear.

I suggest add trade /withdraw to each asset

![ux-1](https://user-images.githubusercontent.com/109044582/178163741-4cf8647b-191c-4406-b292-eca16bcf18b0.jpg)

onchainaddress:{esnpHCUii7PvrGr5d3r2LLSseXzbKteTAsxLGHhhptmL9m4uJ}

**Comment by pavankanteti** [comment]
Doesn't exist in the new version
