### ISSUE TITLE
2 Error messages in Market order while transacting above balance

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#187]
When I entered Sell (Market Order), with 2 values greater than my wallet balance I got the below 2 errors which are not very user friendly. This message needs to be tweaked. But why there are 2 different types of errors? 

Error 1 when entered value is like 1000000000000 - 'createType(OrderPayload):: Struct: failed on qty: u128:: String should not contain decimal points or scientific notation'

Error 2 when entered value is like 1000 - 'invalid number at line 1 column 168'

Is it that Error 1 is when user enters an amount which is greater than allowed limit in a transaction. If so, the message should be made clear. If there is a limit of transaction, ideal way is to make the field restricted so that user cannot enter a value higher than that.

Error 2 should clearly say that 'Insufficient Balance to do the transaction' or so.

onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}

**Comment by jaymansfield** [comment]
Duplicates of #83 and #131
