### ISSUE TITLE
Socket Not Ready error

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#188]
Got an error called Socket not Ready. The error message is not very clear. Can you refine it to more user friendly message? Got it when I tried to execute 

onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}
![image](https://user-images.githubusercontent.com/94037805/178434030-7b16ce2b-6b50-4eaa-a701-0a64d5a47d1e.png)

**Comment by jaymansfield** [comment]
Is this related to #40?

**Comment by pavankanteti** [comment]
This is because the testnet was down at this point.
