### ISSUE TITLE
Unable to Cancel Open Orders

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#189]
Unable to Cancel the Orders as I am getting the error saying - Order not found : 284900843309368233228867881332425120710

onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}
![image](https://user-images.githubusercontent.com/94037805/178531946-874fa843-88da-4f76-9a8a-e7a9ce9fd33f.png)

**Comment by jaymansfield** [comment]
#30

**Comment by pavankanteti** [comment]
Closing as duplicate of #30
