### ISSUE TITLE
Error when trying to Login 

### ISSUE THREAD

**Issue by XBigDeeX** [Polkadex-Substrate/Polkadex-Open-Beta#191]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

![Error Pop-up](https://user-images.githubusercontent.com/86341958/178668011-fe7d6f8b-ea40-41a3-bc4e-d24173b4fe6e.png)

**Description** 

I registered four days ago and was able to access my account. I was swarmed with work so I could not really work on the testnet. I tried logging in and it keeps showing this error without any error message or prompts. I think this can be improved on, telling us what is wrong and how it can be fixed.

I also tried using an incorrect password and I got an error message "Unable to decode using supplied passphrase". I think you can add "Check password and try again." Prompts will make the UI more user-friendly

![Screenshot (46)](https://user-images.githubusercontent.com/86341958/178669133-a3d78eea-59da-4857-85c1-1710367de06d.png)

onchainaddress:{esks8xTZz5xqZjkcNf4RN3TyPgMfhCTDCdGubvYMfpjWp97KB}

**Comment by charleslukes** [comment]
This happened due to expired keys

**Comment by XBigDeeX** [comment]
Alright
