### ISSUE TITLE
Mutiple Proxy Account created because of slow confirmation

### ISSUE THREAD

**Issue by nvmmonkey** [Polkadex-Substrate/Polkadex-Open-Beta#192]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

`![First, I try to create this proxy name but had no luck, because it shows up as "Not Registered" every time.](https://user-images.githubusercontent.com/100928742/178724725-e6a5b1c4-fbb0-43a8-840a-1231b6fa0216.png)`

`![Here you can see because of this error, I create multiple proxy accounts with the same user name.
](https://user-images.githubusercontent.com/100928742/178724896-27b3dc65-1607-4f1d-9a95-8e6d31eb1236.png)`

Aftermath, I tried 3 of these duplicate accounts one by one and was finally able to login into the beta test platform. I think this is a minimal issue for UX "user experience" as it gets confused whether the network is down, or the system is down. It's better to set up notifications or restrictions on how many accounts can be created in a limited period of time.

onchainaddress:{esncv2GZSoJTkwLEnqodEbgRLsSUaAdJUAe4FZsHbDbCyJYY4}

**Comment by pavankanteti** [comment]
This is not valid in the new version. Hence closing.
