### ISSUE TITLE
Suggestion: Allow thea bridge to deposit directly to proxy account (one less step for users transferring in funds to get them to the orderbook)

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#193]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

Suggestion: Allow thea bridge to deposit directly to proxy account (one less step for users transferring in funds to get them to the orderbook)

Or (PREFERRED APPROACH), include thea bridge functionality directly into orderbooks wallet page. Deposit eth straight into the orderbook proxy without needing to leave and goto the token manager

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment]
When trading on Polkadex, your assets are not leaving your main account. We do not take hold of your funds. The proxy account deposit is only a shadow deposit. No actual funds are transferred. They are reserved and new balance state updated upon withdrawal.

**Comment by nlinhmus** [comment]
If it is not possible to send money directly to the proxy account, it is recommended to hide the proxy address (starting with es…), to avoid losing money because users send money to this account from cex.

**Comment by pavankanteti** [comment]
Proxy account doesn't contain any real tokens. They're only a replica of user's intended balances they want to trade with.
