### ISSUE TITLE
Token manager does not load in a mobile browser

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#194]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

Token manager does not load in a mobile browser.

If you are not planning on supporting mobile at the start, you probably should at least display a message explaining that to the user instead of having just a white page

![image](https://user-images.githubusercontent.com/6218678/179046258-ef33c068-d3b4-4dad-8127-11aaab3314eb.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment]
It is not made for mobile browsers as polkadot.js is not supported on mobile browsers.
