### ISSUE TITLE
Error components are stacked on top of each other, creating confusion and bad

### ISSUE THREAD

**Issue by nlinhmus** [Polkadex-Substrate/Polkadex-Open-Beta#195]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Error components are stacked on top of each other, creating confusion and bad.

![67ABCCCC-621B-4B4B-A115-8AEAFDCEC83A](https://user-images.githubusercontent.com/108728380/179225539-b1092a6b-f572-4934-b352-3848768ce898.jpeg)
![2FB83444-CEE0-4C3E-A27B-E4C2D1D17A21](https://user-images.githubusercontent.com/108728380/179225549-f53ed7cc-b2f3-41d7-b143-91f554cee8bd.jpeg)
![7FF5E7CC-2268-43FD-84F9-456D244B63A5](https://user-images.githubusercontent.com/108728380/179225552-f7cff760-2f3e-4d3f-967f-d47e89c13442.jpeg)

onchainaddress:{esnKE5QZ29QaYsCRt7GDynx2pGnr6ZpZJmYYroFMZab8g8Xxk}

**Comment by pavankanteti** [comment]
Site is not made for mobile browsers as we cannot connect to the polkadot.js explorer using mobile browsers. Compatibility might be added in the future.
