### ISSUE TITLE
UI Suggestion for Sign Up Page 

### ISSUE THREAD

**Issue by testnetgbv** [Polkadex-Substrate/Polkadex-Open-Beta#200]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 
Not sure where to proceed after account creation step, perhaps insert a “next” or “sign on” button to proceed with the app on the “Connect to Phone” page 

![Alt Text](https://i.imgur.com/FkX0hKQ.png)

onchainaddress:{ezD41sBLbqRewSQXRbu1XuogNQtm3u3QMKb6eyujojdWMw3so}

**Comment by pavankanteti** [comment]
This suggestion is not valid in the new implementation signup flow. Hence closing.
