### ISSUE TITLE
Ordebook not selling PDEX Limit order at the most recent bid price 

### ISSUE THREAD

**Issue by testnetgbv** [Polkadex-Substrate/Polkadex-Open-Beta#201]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

When selling PDEX, the order was executed at 0.80 instead of 1 

 ![Alt Text](https://i.imgur.com/EQYp37g.png)

onchainaddress:{ezD41sBLbqRewSQXRbu1XuogNQtm3u3QMKb6eyujojdWMw3so}

**Comment by pavankanteti** [comment]
This was because of the desync issue which is fixed now. Hence closing.
