### ISSUE TITLE
No PDEX on wallet - dex fails to deposit even tho orders are fullfiled

### ISSUE THREAD

**Issue by CrazyTachikoma** [Polkadex-Substrate/Polkadex-Open-Beta#202]
![image](https://user-images.githubusercontent.com/109630993/179856734-5685ae10-d6e3-4f97-974c-7eb1da270310.png)

so this happens when I try to sell TDOT for PDEX
the order is actually filled and my TDOT balance went down, but my TPDEX balance is still 0

I've only gotten TDOT from the faucet so my TPDEX wasn't "initialized" I suppose

browser: Edge latest, uBlock disabled

**Comment by pavankanteti** [comment]
This is because of the testnet being down. Closing as irrelevant now.
