### ISSUE TITLE
Markets link from account manager and sign-in/up pages does not work

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#207]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 
Markets link from account manager does not work
![image](https://user-images.githubusercontent.com/6218678/186266607-40c6829a-7aa0-47eb-8b87-0422f37b2d14.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment]
Not applicable in the new design.
