### ISSUE TITLE
Password not long enough

### ISSUE THREAD

**Issue by LunaPolkadex** [Polkadex-Substrate/Polkadex-Open-Beta#210]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

When signing up I get an error message that password is not long enough but don't know lenght required of other requirements.
Please indicate min characters and if capital letters or special characters are required.

onchainaddress:{esnpHCUii7PvrGr5d3r2LLSseXzbKteTAsxLGHhhptmL9m4uJ}

![message](https://user-images.githubusercontent.com/109044582/186271199-fe7bfe6d-22f6-4474-8b2d-403249fc9150.png)

**Comment by pavankanteti** [comment]
Issue not present in the new roll out.
