### ISSUE TITLE
Closing polkadot.js window while linking account

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#211]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

Closing polkadot.js window while linking account freezes page (note: clicking cancel does work as expected but this should perform the same action)
![image](https://user-images.githubusercontent.com/6218678/186271494-1fb1a9ae-e647-4c9e-9ed0-7b59c4bdf3a0.png)

the page is now stuck loading (since transaction wasnt submitted) and i cant re-submit
![image](https://user-images.githubusercontent.com/6218678/186271669-fa9de427-fed4-4d52-b5c7-981d942ef03b.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by minikas** [comment]
Thank you @jaymansfield, if you close the window the event is still pending until you cancel it 
![Screenshot 2022-08-23 at 18 59 37](https://user-images.githubusercontent.com/12574469/186273956-867a61f5-bc56-41a0-8643-a7113814bf0e.png)

**Comment by jaymansfield** [comment]
Same issue on deposit page

**Comment by jaymansfield** [comment]
Ok user error then, closing this
