### ISSUE TITLE
Error importing account

### ISSUE THREAD

**Issue by LunaPolkadex** [Polkadex-Substrate/Polkadex-Open-Beta#215]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

I get an error when I try to import an account

Link points to: https://orderbook-beta.polkadex.trade/importAccount

onchainaddress:{esnpHCUii7PvrGr5d3r2LLSseXzbKteTAsxLGHhhptmL9m4uJ}

![message3](https://user-images.githubusercontent.com/109044582/186274452-a865bb2a-aa8a-402d-a93f-85cb54a0239b.png)

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

**Comment by pavankanteti** [comment]
This is added in the new rollout

**Comment by pavankanteti** [comment]
@minikas please link the pr for reference
