### ISSUE TITLE
UX suggestion

### ISSUE THREAD

**Issue by LunaPolkadex** [Polkadex-Substrate/Polkadex-Open-Beta#217]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

When a adding a trading account the register button is too small.
![message3](https://user-images.githubusercontent.com/109044582/186276073-bd39a2c6-dda8-41e4-9643-f51ef611b98a.png)

Also, once I pick one account I see some distracting links in the page: Create new account | Import
I would add the Create new account | Import at the same level as the Pick account dropdown

![message3 - create](https://user-images.githubusercontent.com/109044582/186275847-0b8f13b9-0cd7-40e6-a795-2418bcbf01e2.png)

Once user picks account, button much bigger like in next step
![message2](https://user-images.githubusercontent.com/109044582/186276007-e7e2ca05-8433-443e-9b16-6751ac7dd569.png)

onchainaddress:{esnpHCUii7PvrGr5d3r2LLSseXzbKteTAsxLGHhhptmL9m4uJ}

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

**Comment by pavankanteti** [comment]
This is not applicable with the new Account Manager implementation
