### ISSUE TITLE
UI: remove extra trailing zeroes

### ISSUE THREAD

**Issue by polkadex-beta-k** [Polkadex-Substrate/Polkadex-Open-Beta#22]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

There are places where you do not need more than one zero to accurately represent the amount. numbers like "5.0000" can be truncated to "5.0" for example.

<img width="299" alt="Screenshot 2022-07-04 at 19 02 07" src="https://user-images.githubusercontent.com/108689740/177201639-927f0747-9cb9-41d0-b0b8-cad9d25db4a0.png">

onchainaddress:{esmTYAxXyJM4siS5nimmqeWcriYGEumnMc7Egofp8KGt8eJKd}

**Comment by charleslukes** [comment]
@pavankanteti not sure what you mean here, could you explain further?

**Comment by cristian-fg** [comment]
this issue doesn't make sense, check kucoin 

<img width="501" alt="Screen Shot 2022-07-07 at 12 02 22 AM" src="https://user-images.githubusercontent.com/53287521/177687986-a0ef7958-b3df-49b7-b40d-c320dc7e06c6.png">

**Comment by charleslukes** [comment]
@pavankanteti is this still valid?

**Comment by pavankanteti** [comment]
This issue is not relevant as we will have dynamically adjusting decimal places in the new implementation, not constant number.
