### ISSUE TITLE
Multiple issues with light mode theme

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#220]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

Connect trading account button text not visible in light mode. White text over a white icon is used.
![image](https://user-images.githubusercontent.com/6218678/186278027-3deaf6c6-2b0e-4d38-895e-b045ee75c1e3.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
Same with circle icon in the top corner it's all black and not visible. Text color needs to be changed for the icon.

**Comment by jaymansfield** [comment]
Another spot:

![image](https://user-images.githubusercontent.com/6218678/186278646-b4f75b42-64fa-4ef8-aa82-a092be8a57c1.png)

**Comment by jaymansfield** [comment]
![image](https://user-images.githubusercontent.com/6218678/186279932-47c908f3-71c5-4218-94e7-0c2b8d9453e9.png)

**Comment by pavankanteti** [comment]
This is fixed now. @minikas please add pr link for reference.
