### ISSUE TITLE
Confusing link "register" trading account

### ISSUE THREAD

**Issue by LunaPolkadex** [Polkadex-Substrate/Polkadex-Open-Beta#221]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

In account manager I have created my trade-account. I have other accounts with "Use" link. When i click i get that error.
I don't understant the message as I would expect a "Register" link instead of "Use"

Cases:
a.- If trading account is not registered -> "Register" link
b.- If trading account has been registered will have a LINK -> "Use" link -> this will swap current trading account for this one
c.- Current trading account will have a TEXT (being used)

It can be more simple to allow users to change trading account with the top dropdown just registered accounts so you need to add a register link to those not registered instead of "Use" and change error message.

onchainaddress:{esnpHCUii7PvrGr5d3r2LLSseXzbKteTAsxLGHhhptmL9m4uJ} 

![message3](https://user-images.githubusercontent.com/109044582/186278863-b5496d19-baea-418d-888f-8a6a27b91a18.png)

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

**Comment by pavankanteti** [comment]
Hi @LunaPolkadex - These other trading accounts that you see, are those old accounts that you added before we made the testnet announcement?

**Comment by LunaPolkadex** [comment]
old ones

**Comment by pavankanteti** [comment]
1. The reason main account couldn't be found was because we restarted the testnet several times in the process
2. Trading accounts cannot be re-registered. They can only be imported.
3. We have implemented a new Account manager flow to make this process much simpler. So you won't see these issues anymore.
