### ISSUE TITLE
Where are my balances?

### ISSUE THREAD

**Issue by LunaPolkadex** [Polkadex-Substrate/Polkadex-Open-Beta#224]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

I claimed 999 test pdex tokens
I have sent 995 pdex from main to trading account 
My balance should be:

Main account: 4 pdex
Trading account 995 pdex

I am in Account manager but I am unable to the balance of each account.

![message3](https://user-images.githubusercontent.com/109044582/186280888-3210416d-ad68-46a9-9fe6-4a467d72e904.png)

Also its very confusing that to send funds from main account to trading account I have to click in deposit link next to main account.

It should be deposit in the trading account.
![message4](https://user-images.githubusercontent.com/109044582/186281563-3520ad68-9779-48da-8cfd-4875b95990d8.png)

This page needs UX fix, check how exchanges show balances and how to move funds from main account to trading account.

onchainaddress:{esnpHCUii7PvrGr5d3r2LLSseXzbKteTAsxLGHhhptmL9m4uJ}

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

**Comment by charleslukes** [comment]
Good question, so the card is clickable, if you click it you will see the available balances the assets you own for that account. 
I think its quite confusing and should be updated to make it more obvious. cc @minikas @pavankanteti

**Comment by LunaPolkadex** [comment]
I understand the card in top right is a quick link to see the available balances but i think this page should show detailed info about assets. 

I also noticed that url is https://orderbook-beta.polkadex.trade/accountManager but in the bottom menu -My profile- under My wallet points to the same url. We should unify names and don't have two names -Account manager & My wallet- pointing to same url. Consider renaming the url.

**Comment by pavankanteti** [comment]
This whole flow is redesigned in the new account manager. Closing issue as invalid for new flow.
