### ISSUE TITLE
Orders are not being filled

### ISSUE THREAD

**Issue by LunaPolkadex** [Polkadex-Substrate/Polkadex-Open-Beta#226]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

15 pdex buy order limit  at 1,00010 is not filled.

onchainaddress:{esnpHCUii7PvrGr5d3r2LLSseXzbKteTAsxLGHhhptmL9m4uJ}

![trading1](https://user-images.githubusercontent.com/109044582/186284961-9162a847-fb06-4c69-b871-832dad064c81.png)

![trading2](https://user-images.githubusercontent.com/109044582/186284971-cb174807-c425-423b-bd09-1a5a62e596c3.png)

**Comment by pavankanteti** [comment]
Because of the known orderbook desync issue, which is now fixed.
