### ISSUE TITLE
Filter for Orders to hide Other Pairs is broken

### ISSUE THREAD

**Issue by mt-gareth** [Polkadex-Substrate/Polkadex-Open-Beta#228]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Filter for Orders to hide Other Pairs is broken, it hides all orders including the one you are on.

![Hide Other Pairs Filter Bug - 1](https://user-images.githubusercontent.com/47789455/186287517-3d02841a-e91d-4569-9cd0-bd6c10d2b7e6.png)
![Hide Other Pairs Filter Bug - 2](https://user-images.githubusercontent.com/47789455/186287536-bfdb3ebb-69ab-4c32-84bf-f92dd3cbfc9f.png)

onchainaddress:{esrCussMhQXzcYQfHkrRFYwfUJq6bfQ4yDg6vbnF2KtpSAqRu}

**Comment by pavankanteti** [comment]
This has now been fixed. @charleslukes is there a change in the pr link? If so please add the appropriate pr for reference.
