### ISSUE TITLE
Orders Not Matching

### ISSUE THREAD

**Issue by mt-gareth** [Polkadex-Substrate/Polkadex-Open-Beta#229]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Orders that have a sell price at or below buy prices are not matching, I think it is due to old orders still showing and they are not actually there.

![Orders Not Matching](https://user-images.githubusercontent.com/47789455/186287695-8debffce-5cf1-475c-b2d8-df80cce34c59.png)

onchainaddress:{esrCussMhQXzcYQfHkrRFYwfUJq6bfQ4yDg6vbnF2KtpSAqRu}

**Comment by pavankanteti** [comment]
This is a known issue and is already there on the Known Issues section as mentioned on the announcement. Closing this as we already have this issue in our internal pipeline.
