### ISSUE TITLE
Sign in/up feedback

### ISSUE THREAD

**Issue by AlesteCapital** [Polkadex-Substrate/Polkadex-Open-Beta#230]
Previous sign in/up feedback [https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/68](url)

I will keep my initial comment as simple as web3 logins should be:
![FXXA9i5aUAAFHmw](https://user-images.githubusercontent.com/91593051/186287554-8c4a0b00-e22c-4fb6-9c5e-90d5677687f3.png)

**Comment by pavankanteti** [comment]
To prevent attacks on the system
