### ISSUE TITLE
Registering Your Main Account creates a Trading account but never shares the seed.

### ISSUE THREAD

**Issue by mt-gareth** [Polkadex-Substrate/Polkadex-Open-Beta#232]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

When you first register your main account the process can create you a proxy trading account, but the seed phrase is never shared for this new account so if lost you would loose access.

![Link_Account___Polkadex_Orderbook - 1](https://user-images.githubusercontent.com/47789455/186288205-268ad3be-4a06-426d-b5ae-c7085d222f61.png)

onchainaddress:{esrCussMhQXzcYQfHkrRFYwfUJq6bfQ4yDg6vbnF2KtpSAqRu}

**Comment by charleslukes** [comment]
@minikas is there a place on the UI we can share seed phrase?
