### ISSUE TITLE
After an additional trading account is made the page does not Account Managment

### ISSUE THREAD

**Issue by mt-gareth** [Polkadex-Substrate/Polkadex-Open-Beta#233]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

After you make an additional trading account the page give you a pop up notification that it was made but the page does not change and the form does not reset. I recommend that it sends you to the Account Management page.

![Create_Account___Polkadex_Orderbook - 1](https://user-images.githubusercontent.com/47789455/186288616-9aa9beab-a555-4371-84c5-8d069e76869d.png)

onchainaddress:{esrCussMhQXzcYQfHkrRFYwfUJq6bfQ4yDg6vbnF2KtpSAqRu}

**Comment by pavankanteti** [comment]
This flow was replaced by the new Account Manager.
