### ISSUE TITLE
Balances Do Not Respect Token Decimal Places

### ISSUE THREAD

**Issue by mt-gareth** [Polkadex-Substrate/Polkadex-Open-Beta#237]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

A token was created with 10 decimal places, 10 tokens were deposited, and the Orderbook shows that only .1 were, Polkadot JS shows it correct.

![Balances Do Not Respect Token Decimal Places](https://user-images.githubusercontent.com/47789455/186298850-5347741e-e032-4ce2-8efc-dad949cb8fcc.png)

onchainaddress:{esrCussMhQXzcYQfHkrRFYwfUJq6bfQ4yDg6vbnF2KtpSAqRu}

**Comment by pavankanteti** [comment]
This was replaced by the new account manager flow
