### ISSUE TITLE
UI: Assets should show asset symbol and name instead of name twice

### ISSUE THREAD

**Issue by mt-gareth** [Polkadex-Substrate/Polkadex-Open-Beta#238]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Your asset list should show the Symbol then the name, instead of the name twice.

![Assets should show asset symbol and name instead of name twice](https://user-images.githubusercontent.com/47789455/186299354-e86774ac-2ade-4286-923b-690a82adcd79.png)

onchainaddress:{esrCussMhQXzcYQfHkrRFYwfUJq6bfQ4yDg6vbnF2KtpSAqRu}

**Comment by charleslukes** [comment]
closing as completed
