### ISSUE TITLE
When signing up it creates a trading account automatically, but does not set it to 'in use' automatically

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#239]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

When signing up it creates a trading account automatically, but does not set it 'in use' automatically which could lead to confusion.

Recommend setting it to 'in use' automatically if its your first one.

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by charleslukes** [comment]
closed as done
