### ISSUE TITLE
Refreshing the page requires me to login again

### ISSUE THREAD

**Issue by polkadex-beta-k** [Polkadex-Substrate/Polkadex-Open-Beta#24]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

From a UX standpoint, it would be great if I did not need to sign in everytime I refreshed the page.

onchainaddress:{esmTYAxXyJM4siS5nimmqeWcriYGEumnMc7Egofp8KGt8eJKd}

**Comment by pavankanteti** [comment]
Closing as duplicate
