### ISSUE TITLE
Issues when main wallet is not selected

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#241]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

Popup from the my profile icon in bottom right corner shows a 0x0000.. address. The popup should say main account not selected and link them to the account page to fix it rather then showing an invalid address.
![image](https://user-images.githubusercontent.com/6218678/186500283-f7c69031-4fb0-4080-92c8-6dd07ea2bfdb.png)

This "My Funds" popup is also slightly misleading when i havent selected my main account yet. It should tell me my wallet hasn't been selected instead of showing no results for funds.
![image](https://user-images.githubusercontent.com/6218678/186500515-405ecdec-79db-49ac-a695-ece1b2694db6.png)
![image](https://user-images.githubusercontent.com/6218678/186500563-2680aa4a-69bc-4317-ab33-37b8657e5b1f.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by charleslukes** [comment]
requires UI change cc @pavankanteti
