### ISSUE TITLE
client-side exception has occurred - TypeError: Cannot read properties of undefined (reading 'address')

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#244]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

Cleared my browser caches and logged in freshly again, then went to the account manager page (https://orderbook-beta.polkadex.trade/accountManager) to setup a trading account and got this error

![image](https://user-images.githubusercontent.com/6218678/186672561-a44e9b00-c8c2-4beb-a5c2-e73307695b0f.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment]
This flow has been replaced by the new account manager.
