### ISSUE TITLE
Create trading account page can be accessed without being signed in at all

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#245]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

Create trading account page can be accessed without being signed in at all

I'm suggesting that you make it forward the user to the signin page if they are not signed in and access that url (this is how the deposit page seems to work if you try to access it while not signed in)

![image](https://user-images.githubusercontent.com/6218678/186716920-80f78dd6-7681-4d34-a1c7-9a986674f7ff.png)

To recreate:
- clear browser cache
- goto https://orderbook-beta.polkadex.trade/createAccount
- 
onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by charleslukes** [comment]
Okay thanks for finding this but you can't create a trading account without signing in. That not how the process works. 
trading account is tied to your main account and your not main account is tied to your email.

**Comment by jaymansfield** [comment]
Understood that you can't have a trading account without signing in, but normally in web apps you restrict access to pages that are meant for signed-in users only. Just a suggestion anyway.

**Comment by charleslukes** [comment]
oh sorry I misunderstood your the issue, we will work on it. Thanks

**Comment by pavankanteti** [comment]
This has been replaced by the new Account Manager flow.
