### ISSUE TITLE
Selling PDEX for TDOT grants no TDOT

### ISSUE THREAD

**Issue by Targan23** [Polkadex-Substrate/Polkadex-Open-Beta#246]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

**Describe the bug**
Selling PDEX for TDOT grants me no TDOT

**To Reproduce**
1. Go to Exchange
2. Click on PDEX-TDOT
3. Scroll right to Sell
4. Sell your PDEX for TDOT
5. Try to buy PDEX for TDOT > no TDOT available

**Expected behavior**
TDOT should be in wallet and ready to sell

**Screenshots**
![image](https://user-images.githubusercontent.com/34280398/186718564-1fe64393-f8ef-4ef7-b448-2ab53c12e6c4.png)

**Additional context**
On chain address: {esouQaHBfnppyHJT7kjmk7BhtL3f9HFgNpnHCqqSpYKcGKwb3}

**Comment by nuel77** [comment]
was you sell order filled by a buyer?

**Comment by Targan23** [comment]
> was you sell order filled by a buyer?

Yes. It was

**Comment by pavankanteti** [comment]
This could be because of an old known desync issue which was fixed. Unable to reproduce.
