### ISSUE TITLE
Incorrect message after depositing funds

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#248]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

I setup a new account and immediatly deposited funds (without creating a trading account)

The status message says successfully deposited to your proxy account, even though I do not have a proxy account yet. Where are the funds then? Should this message be updated if you dont have a proxy yet?

![image](https://user-images.githubusercontent.com/6218678/187002869-222a172e-a638-41b0-9f84-51b5a74f68ba.png)

![image](https://user-images.githubusercontent.com/6218678/187002962-6589c7a7-22d5-41aa-80d6-83676a1a4974.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by nuel77** [comment]
when you registered a account , a proxy/trade account is already created for you. if you havent removed it from blockchain these funds are being added to that account.

**Comment by pavankanteti** [comment]
This flow has been replaced by the new account manager. Although this issue was because of real time updates. You won;t find it in the new account manager.
