### ISSUE TITLE
Text and icons are lost when in light mode due to being obscured by black, the contrast of white and black is annoying!

### ISSUE THREAD

**Issue by nlinhmus** [Polkadex-Substrate/Polkadex-Open-Beta#249]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 
Text and icons are lost when in light mode due to being obscured by black, the contrast of white and black is annoying!
![F0D2E034-D8F2-4159-BD90-0CDADC428FDD](https://user-images.githubusercontent.com/108728380/187010485-5d5a2711-0145-4735-9da9-9248c7bafff0.jpeg)
![9144D8E5-8AAD-402E-B2AB-EB24C417F7D0](https://user-images.githubusercontent.com/108728380/187010488-5196cf1f-f226-42c9-8a69-3f568bd97786.jpeg)
![9DEB5095-E48A-49EE-9AE7-0AD31E18ABB1](https://user-images.githubusercontent.com/108728380/187010489-df8b4cf1-d475-4c71-b601-e965ebc7ce4b.jpeg)

onchainaddress:{esnKE5QZ29QaYsCRt7GDynx2pGnr6ZpZJmYYroFMZab8g8Xxk}

**Comment by jaymansfield** [comment]
#220

**Comment by pavankanteti** [comment]
closing as duplicate of #220
