### ISSUE TITLE
Price units and calendar widgets overlap!

### ISSUE THREAD

**Issue by nlinhmus** [Polkadex-Substrate/Polkadex-Open-Beta#250]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 
Price units and calendar widgets overlap!
![2709A8EE-1375-4EE4-9271-76EF4C28B661](https://user-images.githubusercontent.com/108728380/187032982-e24f049b-613a-4735-84b2-bc32d9f7fdd9.jpeg)

onchainaddress:{esnKE5QZ29QaYsCRt7GDynx2pGnr6ZpZJmYYroFMZab8g8Xxk}

**Comment by pavankanteti** [comment]
@minikas - Please add the relevant pr
