### ISSUE TITLE
Price displayed wrong and out of sync.

### ISSUE THREAD

**Issue by nlinhmus** [Polkadex-Substrate/Polkadex-Open-Beta#251]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 
Price displayed wrong and out of sync.
![D396481A-F5E2-4461-8DA0-45C8D700C09E](https://user-images.githubusercontent.com/108728380/187063549-338f3ace-1ff8-4b72-9061-f4f5a2c18605.jpeg)

onchainaddress:{esnKE5QZ29QaYsCRt7GDynx2pGnr6ZpZJmYYroFMZab8g8Xxk}

**Comment by pavankanteti** [comment]
Time stream would take some time to sync up after an Orderbook recovery. You will not see this all the time. Just for a few moments right after an Orderbook recovery.
