### ISSUE TITLE
UI - Deposit Error has poor language

### ISSUE THREAD

**Issue by mt-gareth** [Polkadex-Substrate/Polkadex-Open-Beta#259]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

When you try to depost an amount that is too low the error shows "Too Short" when it should show something like "Amount Too Low" or better yet "Must Deposit More Than XXX PDEX"

<img width="507" alt="Deposit___Polkadex_Orderbook" src="https://user-images.githubusercontent.com/47789455/192574682-0fc04e00-8b38-420f-810e-7c8d60d139ce.png">

onchainaddress:{esrCussMhQXzcYQfHkrRFYwfUJq6bfQ4yDg6vbnF2KtpSAqRu}

**Comment by pavankanteti** [comment]
https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/439
