### ISSUE TITLE
Wrong proxy account and trades displayed!

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#261]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

Theres a caching issue for trades and stuff..

Step 1 - Create an account and perform trades and then sign out.
Step 2 - Create a second account with a new email. After signing in the trades and trading account from account 1 are still displayed.

![image](https://user-images.githubusercontent.com/6218678/192583284-c95f0f31-49a8-4cd9-bb4c-5afe180ca313.png)

![image](https://user-images.githubusercontent.com/6218678/192583383-8a37c249-9555-4bf1-9b4d-0ddfa8e5a5b9.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment]
Known Issue. Will not be present in the new Account Manager implementation.
