### ISSUE TITLE
Blank error message when trying to withdrawal insufficient funds

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#263]
No error message displayed when trying to withdrawal insufficient funds
![image](https://user-images.githubusercontent.com/6218678/192589089-04b0a01b-1053-463f-9b91-927165899303.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

**Comment by charleslukes** [comment]
fixed in: https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/368
