### ISSUE TITLE
Clicking copy hash of chainbridge transactions copies the string "undefined"

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#267]
Clicking copy hash of chainbridge transactions copies the string "undefined"

![image](https://user-images.githubusercontent.com/6218678/192614420-db6d3686-f848-4ba1-89c3-5b61416e4043.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

**Comment by pavankanteti** [comment]
@nuel77 - Please add pr
