### ISSUE TITLE
Can't create limit order:  "Error in receiving oneshot channel: PriceRangeErr

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#268]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

![image](https://user-images.githubusercontent.com/6218678/192627971-8a224897-04c0-490e-bef9-bf705e44c7eb.png)
onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment]
Adding validations was pending at this time. You won't see this now.
