### ISSUE TITLE
"Recent Trades" not saved across sessions

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#269]
If I make a few trades they show up in the "recent trades" list, but if i then refresh the page the trades I just made are no longer visible and it goes back to a static list showing trades made many hours before.

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by nuel77** [comment]
this has been fixed by changing sorting order from db.
https://github.com/Polkadex-Substrate/orderbook/pull/510
