### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Aravind261197** [Polkadex-Substrate/Polkadex-Open-Beta#270]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Please provide a clear and concise description of the bug you came across/your feedback. Include steps to reproduce and any screenshots if necessary.

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

onchainaddress:{Insert your onchain address within the braces without any spaces}
Letters are
![20220928_113335](https://user-images.githubusercontent.com/114560368/192701722-58974391-f33b-4bc9-b72d-8d25c2a137c7.jpg)
 not visible

**Comment by pavankanteti** [comment]
Closing as duplicate
