### ISSUE TITLE
Place order

### ISSUE THREAD

**Issue by Aravind261197** [Polkadex-Substrate/Polkadex-Open-Beta#272]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Please provide a clear and concise description of the bug you came across/your feedback. Include steps to reproduce and any screenshots if necessary.

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

onchainaddress:{Insert your onchain address within the braces without any spaces}

Not able to place order
![20220928_114555](https://user-images.githubusercontent.com/114560368/192702190-35fb3e63-8269-4c5f-ae8d-c6e9ddc24b9d.jpg)

![20220928_114602](https://user-images.githubusercontent.com/114560368/192702203-12a1bff3-1b99-4062-a64e-9342737884ce.jpg)

**Comment by charleslukes** [comment]
fixed in https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/359
