### ISSUE TITLE
Withdrawal visible 

### ISSUE THREAD

**Issue by Aravind261197** [Polkadex-Substrate/Polkadex-Open-Beta#274]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Please provide a clear and concise description of the bug you came across/your feedback. Include steps to reproduce and any screenshots if necessary.

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

onchainaddress:{Insert your onchain address within the braces without any spaces}

Withdrawal options is not visible
![Uploading 20220928_120146.jpg…]()

**Comment by nuel77** [comment]
The attached image uploaded is not visible. can you add it again?

**Comment by pavankanteti** [comment]
Not enough information
