### ISSUE TITLE
No error message or indication for withdrawal above allowed

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#276]
When withdrawing for an amount greater than available balance, there is no sign to tell user that the amount is greater than balance OR insufficient balance. I would at least expect the Error message to display the error text rather than showing error. 

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

![image](https://user-images.githubusercontent.com/94037805/193069240-0af639cf-1229-404e-bbba-e4c26c127839.png)

**Comment by jaymansfield** [comment]
#263 duplicate

**Comment by pavankanteti** [comment]
closing as duplicate or #263
