### ISSUE TITLE
Notification center issue with mark as read

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#278]
In notification center, when I mark one notification as 'Mark as Read', all the unread messages are moved to Mark as Read. Not sure this is as per design or a bug? If its as per design, I don't understand giving the control to mark as Read at a message level.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

**Comment by jaymansfield** [comment]
Duplicate of #219

**Comment by pavankanteti** [comment]
closing as duplicate of #219
