### ISSUE TITLE
Site is currently vulnerable to click jacking

### ISSUE THREAD

**Issue by polkadex-beta-k** [Polkadex-Substrate/Polkadex-Open-Beta#28]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

To check this, you can use this tool: http://online.attacker-site.com/html5/ClickjackingTester/

Typing in the URL for the orderbook or polkadex.trade site will confirm this. The easiest way to fix this would be to configure the appropriate X-frame response headers

onchainaddress:{esmTYAxXyJM4siS5nimmqeWcriYGEumnMc7Egofp8KGt8eJKd}

**Comment by charleslukes** [comment]
X-frame response headers has been configured and added

**Comment by pdexpab** [comment]
@polkadex-beta-k - ACTION NEEDED 

⚠️ If the issues you've logged are tagged as 'Unconfirmed', your on-chain identity has not been set up yet. Please be sure the issues you have raised on GitHub match up to a verified on-chain identity so your issue can be counted in the overall rewards tally for cycle 1 of Polkadex Open Beta testing. 

If you don't have a verified on-chain identity, follow the steps in [this video](https://www.youtube.com/watch?v=lJh4ROo4SiM) as soon as you can. Please drop us a line here or on Discord once you've done so.

For more details, please refer to the latest message in the Open Beta channel on the Polkadex Discord server and points 3.e and 3.f in [the Polkadex Open Beta Terms & Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)
