### ISSUE TITLE
Cancel not responding to remove unused account

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#280]
Cancel is not responding in accounts manager to remove an account from browser

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

![image](https://user-images.githubusercontent.com/94037805/193083443-ec76d3c3-8bd0-4432-8b57-c0c612714038.png)

**Comment by pavankanteti** [comment]
Flow has been replaced by new account manager.
