### ISSUE TITLE
Remove account pop-up is not auto closing

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#281]
Clicking continue is removing the account from the list, but the pop-up is not auto closing after hitting 'Continue'

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}
![image](https://user-images.githubusercontent.com/94037805/193084130-6ecb5522-0e2e-415f-8c9c-e5e1ee5688e8.png)

**Comment by pavankanteti** [comment]
flow has been replaced by new account manager.
