### ISSUE TITLE
Typo on phrase while removing from blockchain

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#282]
Typo again. no need to have both 'the' and 'your' in the phrase. Eaither use 'in main account' OR use 'in your main account'

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

![image](https://user-images.githubusercontent.com/94037805/193084941-96d4a83b-2479-491a-848c-9007c8793641.png)

**Comment by pavankanteti** [comment]
flow has been replaced by new account manager
