### ISSUE TITLE
Cant missing apostrophe 

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#284]
Small typo again. Cant needs an apostrophe - Can't. Otherwise meaning changed

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}
![image](https://user-images.githubusercontent.com/94037805/193087725-70167b2d-6ca0-4644-ad4f-8fee2911a9e1.png)

**Comment by pavankanteti** [comment]
flow has been replaced by new account manager
