### ISSUE TITLE
Verification Code Page is Accessible without Signup

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#301]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description:
-The verification code page is accessible even if you don't signup, and you will receive username cannot be empty if you press the verify button.

![image](https://user-images.githubusercontent.com/108701680/193239716-b1a5259f-a6fd-4a1f-b3ea-ebd9a4f5c12b.png)

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by nuel77** [comment]
https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/367
