### ISSUE TITLE
New Account is created even without verifying the signup code

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#302]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description:
-New Account is created even without verifying the signup code, you can bypass the signup verification code and directly login!

https://user-images.githubusercontent.com/108701680/193242223-866c1b98-4871-424e-a6f0-35fe1cce1242.mp4

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by nuel77** [comment]
you havent actually logged in as you are not able to access your account-manager and your email is not shown up, but yea when you press the login button its bugging, its should take you the code verification page again.

**Comment by pavankanteti** [comment]
Closed in: https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/363
