### ISSUE TITLE
No check exists to ensure proxy account belongs to main wallet!

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#311]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

I selected a main wallet and trading account and made a trade successfully

I then switched my main wallet to a different wallet and kept the same trading account selected that belonged to the previous wallet, and made a trade again successfully.

System should ensure trading account that is selected belongs to the wallet selected!

In fact, there is also no way in the UI to see which trading account belongs to which wallet.. this could easily lead to users wrongly submitting trades with the wrong wallet if they have multiple

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment]
No more valid with the new Account Manager implementation.
