### ISSUE TITLE
Better error messages for lower quantity orders

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#315]
The error message shown when trying to place a small quantity order is not really insightful. Can we avoid technical jargons in these error messages and simply convey to user what the error means?

The error said: {"errorMessage":"{\"code\":-32000,\"message\":\"Error in receiving oneshot channel: QtyRangeErr(\\\"0.001\\\", \\\"10000\\\")\"}","errorType":"Lambda:Handled"}

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}
![image](https://user-images.githubusercontent.com/94037805/193322063-23f031ed-9053-4f6a-a02b-9c9fdef786c0.png)

**Comment by pavankanteti** [comment]
This won't be relevant with the new trading validation rules
