### ISSUE TITLE
Orderbook withdraw form accepted "1e1" as value

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#317]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

Form accepted "1e1" as a value and passed the form validation.

![image](https://user-images.githubusercontent.com/6218678/193325028-1c17922b-3035-43f1-8e60-76ef44c69dbf.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
Deposit page has the same issue

**Comment by charleslukes** [comment]
fixed in https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/368
