### ISSUE TITLE
Double clicking cancel button on a limit order results in a blank error message

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#318]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

![image](https://user-images.githubusercontent.com/6218678/193336963-6073d859-3772-4d1d-8604-d5d853f3a88a.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment]
Don't let the user cancel the same order twice. The button should be disabled after the first click.

**Comment by charleslukes** [comment]
fixed in https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/371
