### ISSUE TITLE
In markets tab, searching for "FAU" does not find "PDEX/FAU"

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#319]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

In markets tab, searching for "FAU" does not find "PDEX/FAU"

![image](https://user-images.githubusercontent.com/6218678/193366506-d744abd3-4ea7-4ef5-b7d7-235c6b4cf47c.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by charleslukes** [comment]
closed in https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/371
