### ISSUE TITLE
Min Required error? 500000000000 is shown

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#32]
It says Minimum required to transact as 500000000000 for both TETH and TDOT. I think thats not right?

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}
![Min Required is large](https://user-images.githubusercontent.com/94037805/177204457-39c4a3cd-cbf8-4640-9601-d2cf285064a4.png)

**Comment by pavankanteti** [comment]
Closing as duplicate
