### ISSUE TITLE
Periods shown on left side of Calendar is not visible in Dark Mode

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#322]
Months/Weeks shown on left side of Calendar is not visible in Dark Mode

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

![image](https://user-images.githubusercontent.com/94037805/193403754-db93131b-9d2f-42c4-a3a6-97262a7111c1.png)

**Comment by pavankanteti** [comment]
Closing as duplicate
