### ISSUE TITLE
FAU getting deducted for Failed market Buys

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#331]
My Market Buys for PDEX/FAU is getting failed. But I can see that each time the order says failed, FAU is getting deducted from my FAU balance. See revording where I have captured that my balance is getting reduced with each failure.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

https://user-images.githubusercontent.com/94037805/193406611-07372e97-dacd-4b1e-9554-6445afd46c57.mp4

**Comment by nuel77** [comment]
fixed in https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/356
