### ISSUE TITLE
Buying Market error message when no sellers available

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#333]
Use a more UI friendly error for below scenario. User placing Market buy when there are no Sell Orders. Current error message says:
{"errorMessage":"{\"code\":-32000,\"message\":\"Error in receiving oneshot channel: MarketMatchingError(MarketLiquidityError(\\\"10\\\"))\"}","errorType":"Lambda:Handled"}

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

**Comment by jaymansfield** [comment]
Duplicate of #265

**Comment by DayalKS2** [comment]
Not really. Please read description before tagging. The issue I have is the error message is not user friendly or for a non-technical person it doesn't convey anything

**Comment by jaymansfield** [comment]
It’s reporting exactly the same error message

**Comment by DayalKS2** [comment]
Yes and what I am saying in description is to adopt a user friendly error message. A non-technical trader will not be informed when using technical jargons in error messages. For example, 'You cannot place a Market buy order when there are no available Sellers', Or 'The order cannot be processed as there are no immediate buyers/sellers'.....

**Comment by nuel77** [comment]
fixed in https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/356
