### ISSUE TITLE
Total field is blank in Limit Sell

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#334]
In Limit Order Sell, 'Total' field sometimes is not showing any amount despite of allowing user to process to a succesful transaction. Total field just showed 0.000, no matter user adjusted quantity or Price. (Occurs sometimes..I am watching the pattern)

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}
https://user-images.githubusercontent.com/94037805/193407700-c63b88b2-4665-4d0a-846b-5cf35a02d356.mp4

**Comment by charleslukes** [comment]
cant recreate
