### ISSUE TITLE
Unfriendly error message {"arithmetic":"Underflow"} - when trying to deposit insufficient funds

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#34]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

![image](https://user-images.githubusercontent.com/6218678/177204809-5bc4c5ec-78af-4bb0-9a4b-bcf52491cda5.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
Bad error message

**Comment by jaymansfield** [comment]
This can easily happen since the page doesn't tell you your wallets balance. 

https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/7

**Comment by pavankanteti** [comment]
@minikas - error message should be: Insufficient Balance

**Comment by pavankanteti** [comment]
Don't allow deposit if user doesn't have enough funds.

**Comment by charleslukes** [comment]
fixed in: https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/368
