### ISSUE TITLE
Locked Funds but no Open Orders.

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#340]
I have no open Orders, but still I can see balance shown under Locked Funds.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}
https://user-images.githubusercontent.com/94037805/193444645-962f93ed-1141-4806-a67f-661b3f653fb6.mp4

**Comment by nuel77** [comment]
Known issue. will be fixed with next update.

**Comment by nuel77** [comment]
fixed in https://github.com/Polkadex-Substrate/orderbook/pull/510
