### ISSUE TITLE
Sell orders are disappearing from order history/trade history

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#341]
Sell orders are disappearing from order history/trade history

I create the order with timestamp at 10:04am, it is then gone after switching tabs

https://user-images.githubusercontent.com/6218678/194572501-64d6a5a7-b9aa-44f5-89a7-d7f742cde40d.mov

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
Just noticed the 4 orders i made show up in the "recent trades" box (the ones with 0.25 as the amount) but none are visible in open orders/order history/trade history anymore.

**Comment by nuel77** [comment]
this is a known issue. Fixe coming out soon. Try selecting `last week` on your calendar it should show your orders again.

**Comment by pavankanteti** [comment]
@charleslukes - Please add the pr where you fixed this.

**Comment by charleslukes** [comment]
here: https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/361
