### ISSUE TITLE
Missing the option to retrieve the account login password if you forgot the password, suggesting the google sign-in feature..

### ISSUE THREAD

**Issue by nlinhmus** [Polkadex-Substrate/Polkadex-Open-Beta#349]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 
Missing the option to retrieve the account login password if you forgot the password, suggesting the google sign-in feature..

![4726DD62-37A2-4BE5-86C4-E9B5504BAED1](https://user-images.githubusercontent.com/108728380/197310783-b38434d1-149b-414f-9135-a12ee507a974.jpeg)

onchainaddress:{esnKE5QZ29QaYsCRt7GDynx2pGnr6ZpZJmYYroFMZab8g8Xxk}

**Comment by pavankanteti** [comment]
Forgot password field added
