### ISSUE TITLE
Ledger Wallet Registration Issue

### ISSUE THREAD

**Issue by AlesteCapital** [Polkadex-Substrate/Polkadex-Open-Beta#354]
When trying to register a Ledger wallet account to create a trading account, the following issue arises: 

<img width="555" alt="Screenshot 2022-10-31 at 22 18 50" src="https://user-images.githubusercontent.com/91593051/199046450-e42b4630-c732-4abd-909b-f63a58ecb059.png">

onchainaddress:{esmeLodChfopvWXMNjmNoGhP3kUHr3RLVKn9DzoSjai5aautg}

**Comment by pavankanteti** [comment]
This should be fixed by ledger app. They're not supporting raw data signing.
