### ISSUE TITLE
Privacy and Terms and Conditions  - Wrong navigation

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#37]
Clicking Privacy and Terms and Conditions taking user to Orderbook url. 

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

**Comment by pavankanteti** [comment]
Closing as duplicate
