### ISSUE TITLE
Alphabets and Successful Deposits

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#380]
Alphabets when combined with numbers are still allowing incorrect deposits. It allowed user to input 0o15 (with alphabet o), and hit Deposit and this deposited 13 PDEX in the process!!! 

If alphabets and special chars are causing issues, then restrict user from entering these in Token Amount field.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

https://user-images.githubusercontent.com/94037805/201280917-1b09944a-4ba7-44f9-9a94-369a31bfe18d.mp4

**Comment by pavankanteti** [comment]
Unable to replicate. Looks like this is a duplicate issue.
