### ISSUE TITLE
Random Errors when navigating back and forth from Balance and Withdraw

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#386]
I am getting random Error screens without any messages. This is happening when I am going back and forth from one module to other. See recording.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

https://user-images.githubusercontent.com/94037805/201292886-4110f7ff-727f-46ce-afba-f3e0b876803d.mp4

**Comment by pavankanteti** [comment]
Unable to replicate
