### ISSUE TITLE
Default Flag is not reverting for Funding Account when Trading Account  default flag is turned off

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#388]
I am not sure how Default Funding Account is assigned in Accounts page. I remember selecting default trade account where I had switched it on for one of my trading accounts (DKS PDEX). I guess during that time, it automatically tagged the mapped funding account  (DKS17) as 'default funding account'. If that is correct, then that tag is not getting removed/reverted when I turn off the default flag for my Trading Account. In my case, I have switched off the Default flag for all my Trading Accounts. But this didnt revert the Default flag for corresponding Funding Account. For DKS17, I still see the flag as ON.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

![image](https://user-images.githubusercontent.com/94037805/201295798-08399d11-0e32-4d8f-a7d3-5f87b95fa045.png)

**Comment by nuel77** [comment]
fixed in https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/439
