### ISSUE TITLE
Disallow negative numbers when depositing

### ISSUE THREAD

**Issue by polkadex-beta-k** [Polkadex-Substrate/Polkadex-Open-Beta#41]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

The field to enter the deposit amount, does not give an error message, when I type a negative number. For UX, it would be good to either disallow it, or have an error message. When you type in a letter for example, it gives an error message.

Screenshot of message when you put letters:

<img width="785" alt="Screenshot 2022-07-04 at 19 58 47" src="https://user-images.githubusercontent.com/108689740/177206493-aff8f83c-0197-4065-a910-f8461104e891.png">

Screenshot with no letters but still has minus:

<img width="787" alt="Screenshot 2022-07-04 at 19 59 19" src="https://user-images.githubusercontent.com/108689740/177206534-a74c5aac-1666-47a5-b49d-bc8d0dc25561.png">

What happens when you click deposit with a minus number

<img width="3200" alt="Screenshot 2022-07-04 at 19 59 45" src="https://user-images.githubusercontent.com/108689740/177206575-abbe163e-670f-40e6-bf87-232ad69cdbba.png">

onchainaddress:{esmTYAxXyJM4siS5nimmqeWcriYGEumnMc7Egofp8KGt8eJKd}

**Comment by jaymansfield** [comment]
Duplicate #23

**Comment by pavankanteti** [comment]
Closing as duplicate
