### ISSUE TITLE
Mainnet orderbook error - "cannot read properties of undefined (reading 'm')

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#416]
Mainnet orderbook error - "cannot read properties of undefined (reading 'm')

Occurred when I just opened the page for the first time today. After refreshing the error went away.

![image](https://user-images.githubusercontent.com/6218678/201412368-06a2ed6c-187b-4c0d-8ec9-f5d38cdb6efb.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by nuel77** [comment]
heppened due to small network error that happened in our systems. should be fixed by now

**Comment by nuel77** [comment]
reopen if its still there.
