### ISSUE TITLE
Amazon SES Config Error for email

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#418]
When trying to Sign up an account, I got an error saying - Exceeded daily email limit for the operation or the account. If a higher limit is required, please configure your user pool to use your own Amazon SES configuration for sending email.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}
![image](https://user-images.githubusercontent.com/94037805/201505926-713880aa-bc65-406f-8db5-76412d5b77cb.png)

**Comment by pavankanteti** [comment]
This is because of total number of accounts per day limit. This has been increased.
