### ISSUE TITLE
Error: This proxy account has not been registered yet!Name of the Issue 

### ISSUE THREAD

**Issue by Brannerz** [Polkadex-Substrate/Polkadex-Open-Beta#42]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Please provide a clear and concise description of the bug you came across/your feedback. Include steps to reproduce and any screenshots if necessary.

Receive error Error: This proxy account has not been registered yet! when logging in proxy account after successful proxy account registration message during signup 

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

onchainaddress:{Insert your onchain address within the braces without any spaces}

esrXSHjuDT37eeGbSYrtpduS4h8yQ2Sv8GjYc6nKoHYuQj7YU

**Comment by pavankanteti** [comment]
This is a know issue from our side and we have fixed this already.
