### ISSUE TITLE
Funding account not refreshed

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#432]
Funding Accounts are not refreshed as per user's uipdated accounts. i had deleted and added new account to polka js. I dont see them under Fundings Account as updated. It's not that i had not reloaded the page. I had actually reloaded the page by going to Market page, then visisting Exchange and then re-visisted Account page. But even then the Funding Accounts displayed are not refreshed as per my wallet. To get it updated, I had to refresh the url

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}
https://user-images.githubusercontent.com/94037805/202612015-ad2e5093-0bbe-4ff7-8b95-cc558b8de344.mp4

**Comment by pavankanteti** [comment]
This is not present in the new UI.
