### ISSUE TITLE
Bridged FAU from ethereum and wrong amount was deposited to my account. Funds lost?

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#443]
Bridged FAU from ethereum and wrong amount was deposited to my account!

This morning I bridged 100 FAU from ETH to POLKADEX.

![image](https://user-images.githubusercontent.com/6218678/206460647-c8034a10-85dd-4683-b9d9-ae3ac66217c3.png)

The bridge was super fast today and only took a few minutes.

However, only 0.0001 FAU was deposited to my account??

From token manager:
![image](https://user-images.githubusercontent.com/6218678/206461591-6fab0384-ba8e-465a-b087-19f966bae119.png)

From orderbook deposit page:
![image](https://user-images.githubusercontent.com/6218678/206460887-6a49ce91-3329-4e7e-9dc0-a6b8c0317e48.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by nuel77** [comment]
Can you send the transaction id for this on ether scan?

**Comment by jaymansfield** [comment]
@nuel77 https://sepolia.etherscan.io/tx/0x429241d8feae39a66542496da6c8a45836fa0227acff599c8f7a2bd277f40da7

**Comment by pavankanteti** [comment]
This can't be reproduced now. It could have been because of the way the token decimals are configured at that time.
