### ISSUE TITLE
UI Visual suggestion: Centralise and make Dark Mode/Light Mode toggle switch circular

### ISSUE THREAD

**Issue by Adam-ation** [Polkadex-Substrate/Polkadex-Open-Beta#45]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

I suggest to make the Dark Mode/Light Mode toggle switch circular, and also make it central as it is currently favoring the right side.

[Example](https://www.dropbox.com/s/psietbqihmyo8de/Toggle_Suggestion.jpg?dl=0)
![Toggle_Suggestion](https://user-images.githubusercontent.com/21147893/177211752-49e9fa9c-391c-433e-985b-538bece1452f.jpg)

onchainaddress:{esouBHidHLoemoG1RA43jGt2MarKsBxGRWyAEFBdrZdjixwDx}

**Comment by minikas** [comment]
Thank you @Adam-ation  I liked your suggestion

**Comment by Adam-ation** [comment]
It looks great @minikas, Thankyou.
