### ISSUE TITLE
Withdrawal Stuck Pending

### ISSUE THREAD

**Issue by Targan23** [Polkadex-Substrate/Polkadex-Open-Beta#450]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Used the withdraw PDEX function but it is stuck on Pending.

![image](https://user-images.githubusercontent.com/34280398/213467113-66ed1a71-27f9-4ce2-9aef-fff5765377bc.png)

Steps:

1. Accounts > Add funds > Withdraw PDEX > 8 PDEX coins and hit Withdraw
2. I have received the Notification "Withdrawal Successful" but it is stuck in Pending

![image](https://user-images.githubusercontent.com/34280398/213467771-7a1c8279-9297-4ac3-bac9-1faa8352b201.png)

As you can see the date (Jan 19, 2023, 04:25 PM) keeps changing every time i refresh the page to display the current date, and the status is still Pending.

You can also see that there is nothing under Ready to claim tab.

![image](https://user-images.githubusercontent.com/34280398/213468097-c0426fa1-e761-46c8-8085-2213d147d392.png)

Or Claimed.

![image](https://user-images.githubusercontent.com/34280398/213468169-c86c8952-2187-42d5-9684-fa8ea130aa62.png)

UPDATE:

After the annoucement that the bug was fixed i have checked and still both my withdrawals were shown as Pending.
I have checked next day and only one is Ready to claim. (i have made 2 withdrawals at approximately the same time: one of 8 PDEX and one of 1 PDEX) while the other one still shows as Pending.

## Pending ##
![image](https://user-images.githubusercontent.com/34280398/213656718-c43a6c52-1387-4360-b5dd-cb87c8dffa0b.png)

## Ready to claim ##
![image](https://user-images.githubusercontent.com/34280398/213656779-56a645bb-8d56-4e09-ad24-e510c203cc49.png)

UPDATE: After i have submitted the Claim. I have received the notifications that 'Claim withdraw successful' however, the withdraw didnt happened and i still have the option to Claim my assets.

![image](https://user-images.githubusercontent.com/34280398/213657899-19528a04-4bbd-4b06-a981-661c82941fe4.png)

UPDATE: Tried a second time to Claim. Same thing. Received notification that it was successful but nothing happens.

![image](https://user-images.githubusercontent.com/34280398/213658377-2f3f10fc-2cff-44a8-b444-5d8d510e55bb.png)

onchainaddress:{esouQaHBfnppyHJT7kjmk7BhtL3f9HFgNpnHCqqSpYKcGKwb3}

**Comment by nuel77** [comment]
are you still getting this issue?

**Comment by Targan23** [comment]
Hi. Yes. I still have this problem. Or at least the second part.
Now, both transactions show up on the Ready to claim tab.
However, 2 seconds ago i have tried to Claim one of them and i got Success

![image](https://user-images.githubusercontent.com/34280398/213676300-2107be65-8bd1-48bf-a870-c9ff1f29592b.png)


But It wasnt claim.

See Claimed tab:

![image](https://user-images.githubusercontent.com/34280398/213676434-aa20bbea-cfcb-4e6f-a97d-ab4c52f5f787.png)


While Ready to Claim tab still has the 2 orders set as Ready:

![image](https://user-images.githubusercontent.com/34280398/213676522-66ec50ac-e5ea-4c7f-bf33-585f6726e323.png)

**Comment by Targan23** [comment]
P.S I just checked on chain and it seems i have received the both the 8 and 1.

![image](https://user-images.githubusercontent.com/34280398/213680381-d6c39f90-267c-41f1-8725-5eecdfafa411.png)


However my TAB still shows like this.

![image](https://user-images.githubusercontent.com/34280398/213680469-14c253e2-e040-4455-a95c-838e8b5b31a1.png)


Also i am not sure if i really received the 8 and 1 on my address because i dont know the exact sum i had in my account. But its probably correct.

**Comment by Targan23** [comment]
Another thing: Even if the PDEX was actually claimed, the Ready to claim still shows the PDEX AND if you try to Claim, you will be taxed accordingly.

Check my screenshot of the taxes i payed while trying to Claim. (From Nova Wallet History)

![image](https://user-images.githubusercontent.com/34280398/213754209-2830d6dc-ae35-403e-8bcd-3611d26df1a3.png)

**Comment by pavankanteti** [comment]
Even if the claim doesn't go through, the blockchain will charge for the computation. Hence the fee. But the claim issue has long been fixed.
