### ISSUE TITLE
Select address issue

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#46]
In Wallet, the account is pre-selected and it appears that user need to enter only Token and Amount. But 'Required' mark appears under the Account and user has to click the dropdown and select the address again. Either you shouldn't be pre-selecting the address for user and let user select the address manually. If Not, dont ask the user to select the address again!!

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

![image](https://user-images.githubusercontent.com/94037805/177207710-ef871e47-bd99-439d-9e0e-faa7d938b1fe.png)

**Comment by jaymansfield** [comment]
Running into the same issue as this. Need to select it a second time

**Comment by pavankanteti** [comment]
Closing this as duplicate. Already fixed.
