### ISSUE TITLE
Orderbook buy/sell wall, sum in quote price is incorrect

### ISSUE THREAD

**Issue by zeshanjum** [Polkadex-Substrate/Polkadex-Open-Beta#463]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

As you can see, other than one or two entries the sum of quote price is incorrect deep down the sell/buy wall.

![Screenshot 2023-03-03 233742](https://user-images.githubusercontent.com/37186250/222802769-e6e21979-2648-4f5d-8193-53c93868104f.png)

onchainaddress:{esrFTmBAFR1vzbTtqoCbj453geXZAnMLRKRrHorLmxVpsc8UR}

**Comment by jaymansfield** [comment]
The numbers look correct.. you need to take into consideration its cumulative.

For example on the buy table:
1.93 * 68.1 = 131.433
(1.89 * 100) + 131.433 = 320.4333
(1.88 * 100) + 320.4333 = 508.4333
