### ISSUE TITLE
Enhancing UI experience when placing an order

### ISSUE THREAD

**Issue by zeshanjum** [Polkadex-Substrate/Polkadex-Open-Beta#468]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

It is really helpful when orderbook retain the inserted price and amount value when switching from sell to buy and vice versa when placing a limit order. sometime user insert value to bid and later notice that he is on the sell side of placing order, and has to switch to buy side, inserting value again is a bottleneck.

similarly switching from limit order to market order, it is helpful if the orderbook retain the amount value or price value which one is more appropriate. and vice versa.

placing a market order it is helpful if the price inserted actually show you an estimate of the quoted amount based on the best available price, and vice versa, and other info like fees etc in real time.

there is no slippage selection. i hope it will be added soon.

An example from other dex
 
![Screenshot 2023-03-06 225537](https://user-images.githubusercontent.com/37186250/223192657-07b154b4-4374-45ba-b197-3595e210ae71.png)

onchainaddress:{esrFTmBAFR1vzbTtqoCbj453geXZAnMLRKRrHorLmxVpsc8UR}

**Comment by ap211unitech** [comment]
Here is the PR which fixes this issue - https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/589
