### ISSUE TITLE
Orderbook deposits allow more decimal places then shown in UI

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#472]
I was successfully able to deposit 10.000000000001 PDEX, but the UI does not show that many decimal places so under balances I can only see 10.00000000. 

Basically don't allow the user to deposit an amount with over 8 decimal places if the UI won't display it.

![image](https://user-images.githubusercontent.com/6218678/225314261-3d4a652f-857a-4dcb-b58e-13a5297472d9.png)

![image](https://user-images.githubusercontent.com/6218678/225314212-ed051046-6846-4ba0-89a7-9fffe0687c00.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by ap211unitech** [comment]
Here is the PR - https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/661
