### ISSUE TITLE
Unable to import wallet

### ISSUE THREAD

**Issue by jcbm123143** [Polkadex-Substrate/Polkadex-Open-Beta#48]
<img width="960" alt="IMPORT WALLET" src="https://user-images.githubusercontent.com/22148449/177208132-87b71e74-7e30-478a-8106-2715e3f7a2d5.PNG">

onchainaddress:{esqyaynftRoreLfX2tsUN6rUzoN6zmoWYgnvzmcgV7yJvC9on}

**Comment by jaymansfield** [comment]
Might be related to #5

**Comment by pavankanteti** [comment]
Closing as duplicate of #5
