### ISSUE TITLE
Thea Page going blank after clicking Refresh

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#488]
After logging to Thea and going to Asset Page, and clicking Refresh, the page goes blank. This is consistent issue. Console shows some error message as shown in recording.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/94037805/359a47d7-eb79-42e8-b9a1-c1a1085c4636

**Comment by ap211unitech** [comment]
Here is the PR - https://github.com/Polkadex-Substrate/Polkadex-UI/pull/130
