### ISSUE TITLE
Wrong Notification in Thea page for Moonbeam Connectivity

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#489]
I doubt the connectivity messages fired in Thea is correct. Even before I downloading Talisman Extension, when I visited Thea page, it shows 'Connected to Moonbeam Alpha'. Its a wrong message as I have not connected yet.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

**Comment by pavankanteti** [comment]
Hi - The app itself is connected to Moonbase Alpha. That is what this means.
