### ISSUE TITLE
Orderbook - Unable to withdrawal remaining GLMR 

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#504]
Unable to withdrawal remaining GLMR from orderbook

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/f47bcc63-1429-48bc-a8de-7da556a8f16d)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
15+ minutes have now passed. Still can't see transactions?

**Comment by ap211unitech** [comment]
Here is the PR - https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/660
