### ISSUE TITLE
THEA - Unable to deposit GLMR - failed to approve sign request

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#509]
Happens after clicking the approve button.

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/a24dbf26-3d1f-4f2f-bf5b-287cf41ea3db)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
Updated chrome and it seems to no longer get the error

**Comment by pavankanteti** [comment]
Closing as the chrome update fixed this
