### ISSUE TITLE
Multiple Error Message in Accounts page

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#514]
Encountered issue in Orderbook, where I am not able to add Trading Account. Then I went back to Market and hit 'Select Account' for Trading Account. Then below page appeared with multiple Error messages displayed all along.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}
![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/94037805/e0007738-3012-4bcd-8334-338a478a53ba)

**Comment by pavankanteti** [comment]
https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/640
