### ISSUE TITLE
Dont Show again checkbox is not responding in Thea

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#533]
In Thea, Don't show again checkbox is not working for the User Navigation Guide. I have checked it multiple times. But next time when I go back to Deposit, I am still seeing the guide

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/94037805/4db8999e-413d-4581-a010-644dc1a1f497

**Comment by ap211unitech** [comment]
Here is the PR - https://github.com/Polkadex-Substrate/Polkadex-UI/pull/149
