### ISSUE TITLE
Thea: automatically changing me from dark mode to light mode 

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#534]
Thea: Changing from one menu to other menu is automatically changing me from dark mode to light mode 
onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/94037805/1f59db22-d60b-4768-891f-9d976fdad3d5

**Comment by ap211unitech** [comment]
Hey @DayalKS2 , Can u confirm this issue again because I am not facing it. I tried many times but didn't face this. Let me know if you face it again.

**Comment by ap211unitech** [comment]
Here is the PR - https://github.com/Polkadex-Substrate/Polkadex-UI/pull/153
