### ISSUE TITLE
THEA - "Dont show again" for popup tutorial is not working

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#536]
"Dont show again" for popup tutorial is not working

https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/b9b10c5b-86ed-4d4b-b284-d287b634acfe

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by ap211unitech** [comment]
Duplicate of https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/533
