### ISSUE TITLE
When logged out, connect your account button does not work on orderbook ui

### ISSUE THREAD

**Issue by polkadex-beta-k** [Polkadex-Substrate/Polkadex-Open-Beta#54]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

- To reproduce, navigate to the orderbook.
- Refresh the page, so you are logged out
- Then click "connect your account"

<img width="305" alt="Screenshot 2022-07-04 at 20 33 34" src="https://user-images.githubusercontent.com/108689740/177209384-9ba651b4-c15f-4316-86fe-d83292dedb00.png">

onchainaddress:{esmTYAxXyJM4siS5nimmqeWcriYGEumnMc7Egofp8KGt8eJKd}

**Comment by polkadex-beta-k** [comment]
Also the two "Total" labels are not aligned which would be good

**Comment by pavankanteti** [comment]
Fixed in the new implementation
