### ISSUE TITLE
Can't login with registered account.

### ISSUE THREAD

**Issue by holdemupholders** [Polkadex-Substrate/Polkadex-Open-Beta#55]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

After registering account, a notification is received upon login that the account is not registered. 

Screenshot 1: account creation is initiated
2. Account registration is successful
3. Login prompts that account is not yet registered. 

Cannot login and use test net. 
1. ![Screen Shot 2022-07-04 at 2 26 31 PM](https://user-images.githubusercontent.com/79729027/177209730-f22ffbac-54fe-437d-86ec-7c129d348df4.png)
2. ![Screen Shot 2022-07-04 at 2 27 18 PM](https://user-images.githubusercontent.com/79729027/177209915-68335507-c19e-4260-aa81-afe887b559aa.png)
3. ![Screen Shot 2022-07-04 at 2 54 20 PM](https://user-images.githubusercontent.com/79729027/177211015-4af6baa2-18c1-4d00-917c-cd2598f6604f.png)

onchainaddress:{esqm4KnSyebv7Cap4oRm7EHbxSne1c7anLn6tQQSx6zDTyVE7}

(Is this why my account in github is unverified?)

**Comment by jaymansfield** [comment]
Select the proxy account you created on the login page (in the screenshot you are trying to log in by selecting the main account instead)

**Comment by holdemupholders** [comment]
> Select the proxy account you created on the login page (in the screenshot you are trying to log in by selecting the main account instead)

I (re)took correct screenshot now. Still doesn't work.

**Comment by holdemupholders** [comment]
> Select the proxy account you created on the login page (in the screenshot you are trying to log in by selecting the main account instead)

That account original Pdex Test ESNW account isn't an option in the drop down screen on login. And, I think that's the problem.

**Comment by holdemupholders** [comment]
> Select the proxy account you created on the login page (in the screenshot you are trying to log in by selecting the main account instead)

Just created a new js. account, received test tokens, carefully registered account and tried to login with the new account, and still says account is not registered. Cryptozody, Lee, and Leo have experienced the same problem. If you try to create a new account, or log out and log back in, you may experience it too.

**Comment by pavankanteti** [comment]
Testnet was down during this time. You shouldn't face this issue now.
