### ISSUE TITLE
OrderBook - can't place limit sell order

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#568]
Button is greyed out

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/56447c94-0f3a-4b0b-8a58-e2f92d0a6cef)

**Comment by jaymansfield** [comment]
Posted on request of DreamNetwork

**Comment by nuel77** [comment]
Working on patch here.

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/810
