### ISSUE TITLE
OrderBook- Funding account balance doesn't refresh after successful transfer

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#579]
The funding account balance does not get refreshed after doing a transfer.

I had 11.5 USDT in my funding account and then transfered 5 USDT to my trading account. My funding account balance still showed 11.5 USDT in the UI instead of 6.5 USDT.

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/011af96c-b0ef-42fe-9a25-8c2a3418ae6f)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
Even hitting the big green "switch" button in the center doesn't actually refresh balances. I had to completely leave the page and come back to see the proper balance

**Comment by ap211unitech** [comment]
Hey, We fixed it now. Currently, it's not in main branch but probably it will be there in couple of days.
 
Here is the PR - https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/904
