### ISSUE TITLE
OrderBook - Unable to place market order - Not enough liquidity error even when orders exist

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#580]
Unable to place market buy for PDEX/USDT even when the orderbook is showing liquidity.

Was able to reproduce a few times using this amount: 0.01 USDT

It looks like maybe the trade goes through my balance is reduced even though I'm given an error message.

See video:

https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/4e640232-8713-4988-b03d-a4b733c12bf1

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
This is still happening.

I just tried a $5 market order of DOT and got:

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/c2cbce47-2733-4632-9573-77dc5e863b93)

**Comment by nuel77** [comment]
A tiny quantity is not getting processed during market bids due to precision constraints. 99.999% of the order is consumed though.  But yea showing the liquidity error is confusing.
