### ISSUE TITLE
OrderBook- registered a second funding account and balances are not shown for it

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#581]
I registered a second funding account and the OrderBook is showing my balance as 0 even though I have funds in it.

funding account: esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ
trading account: esmmYUi88HByiQuAagnCheJEmxayA1pNmmmqUqb1MPENz1hd3

orderbook:
![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/9eb227b8-e47d-459b-8aee-38cc428c9b37)

thea which shows the correct balances:
![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/dc568bf5-ae38-4c60-85a3-0c32e8b96e88)

The issue seems to stem from the graphql API itself:

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/c651191a-f61a-4a06-b95a-6eb892059546)
![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/9659436e-aa76-4c80-8712-ba15a6733365)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by nuel77** [comment]
could you try it in the internal [link](https://orderbook-internal.polkadex.trade/) . We added some fixes for the realtime update of onchain balances there.

**Comment by jaymansfield** [comment]
@nuel77 same issue on internal link. balances are showing as 0.

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/22f23f6d-c0b9-46d6-b02f-f83250775436)

funding account: esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ
trading wallet on internal link is espJ4QZ6cKjgVBk3JHHg2YNw9CxiJqy9iKphGbBrkqkP7SxZa

**Comment by ap211unitech** [comment]
Hey, It's been fixed now. You can see the changes in couple of days

PR - https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/907
