### ISSUE TITLE
OrderBook - Inconsistent balances shown

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#583]
I just noticed theres an issue with my DOT balance shown on the orderbook.polkadex.trade

It's different in two spots:

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/4e1b54e5-b057-48f7-902b-66e3043ac475)

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/348885ad-f779-4256-a5c8-14e2f0e12c48)

trading account:esmuPSguC6ikSgWCo7toNjguFRp8WNqrWqn6HwQiiT7H9H3dc
funding account: esnbKSRnU1WKNgJewte4asokmCWwiKBL2HeVWS3NSYEiZfoYc

I'm not sure which should be correct. The last thing I can remember doing was cancel an open order.

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
I'm not sure which should be correct. The last thing I can remember doing was cancel an open order.

**Comment by jaymansfield** [comment]
I just tried orderbook-internal.polkadex.trade and there seems to be a different issue there.

The funds tab matches the balances page:
![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/671ded01-2004-4ed5-b7c2-89a3308b6fa5)

But I see this:

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/40834968-20ed-4d13-b506-9914a3a860e1)

**Comment by ap211unitech** [comment]
Hey, It was an issue with calculations, your DOT balance is 0 i.e. 7.575*(10^-6). So, it's been rendering wrong in balances table and in funds tab. You can see the fixes soon on internal website. and would be reflected in main website in couple of days.

Here is the PR - https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/912
