### ISSUE TITLE
OrderBook- Backspace character breaks trading password input

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#584]
User gets stuck after trying to erase a character. 

Right now once backspace is used once, they must erase the entire password entered before they can enter a number again.

It needs to be more user friendly and intuitive.

https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/4306604b-1bb2-4f89-9df6-7d6a31a3ee63

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by ap211unitech** [comment]
This is fixed now.

PR - https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/918
