### ISSUE TITLE
OrderBook - Wallet page tour has duplicate text

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#585]
Page shows duplicate text and it seems to be text about a funding account and not a trading account

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/0d81412c-010f-4106-bab2-74cbdbae1e53)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by ap211unitech** [comment]
This is fixed now.

PR - https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/918
