### ISSUE TITLE
THEA crashing after loading pdex wallet - client-side exception has occurred

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#586]
Application error: a client-side exception has occurred (see the browser console for more information).

TypeError: invalid FixedNumber string value (argument="value", value="0x00000000000000000036124cd7afa743", code=INVALID_ARGUMENT, version=6.2.3)

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/f5b04c6b-2203-4abf-a03a-c2106447e118)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by ap211unitech** [comment]
Hey, Can u try to replicate it in private/incoginito window. Let me know if it's there as well. Also, Please let me know which extension wallet are you using.

**Comment by jaymansfield** [comment]
@ap211unitech Yes it happens in private/incognito as well. 

I checked a number of wallets and it only happens when I connect to one of them. This one: esnbKSRnU1WKNgJewte4asokmCWwiKBL2HeVWS3NSYEiZfoYc

I've traced through the minified code in the console and could see that it's the circled value in this object that its failing to parse which looks to be my pdex balance

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/25d54480-b7a5-4531-a20c-e7cd0a006e02)

When I load other wallets this free pdex value isn't in hex like that. Could that be the issue?

**Comment by ap211unitech** [comment]
Thanks for your efforts @jaymansfield . We are working on it.

**Comment by ap211unitech** [comment]
Hey, Can u check again if THEA is crashing for you with the same account.

THEA Link - https://thea.polkadex.trade/

**Comment by jaymansfield** [comment]
@ap211unitech  Looks like its working now!
