### ISSUE TITLE
THEA asset balances do not automatically refresh after claiming deposit

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#597]
After someone claims a deposit you should refresh all balances automatically. I claimed on the transactions page and switched back to assets and it had my old balances still. I had to manually click refresh.

onchainaddress:{esrFTmBAFR1vzbTtqoCbj453geXZAnMLRKRrHorLmxVpsc8UR}

**Comment by ap211unitech** [comment]
Fixed now.
