### ISSUE TITLE
Buy and sell orders for the same amount not matching

### ISSUE THREAD

**Issue by mt-gareth** [Polkadex-Substrate/Polkadex-Open-Beta#6]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

I created a Buy order for the same price as an existing sell order, it is made but not automatically matched, showing a buy and sell order for the exact same price.

**Note** :You can see the buy order I made and the sell order that was already there, same price, no match.: ![Alt Text](https://user-images.githubusercontent.com/47789455/177198225-ffbf0552-73e9-4196-98f5-9748b811c22d.png)

onchainaddress:{esrCussMhQXzcYQfHkrRFYwfUJq6bfQ4yDg6vbnF2KtpSAqRu}

**Comment by pavankanteti** [comment]
same problem as #174
