### ISSUE TITLE
Suggestion: verbiage change for "other trading accounts"

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#613]
It's not clear to the user that these belong to different funding accounts. Maybe the verbiage can be changed to specify this.

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/ac85d2b5-bbf3-4ec9-9cd2-e06ffaa2084d)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by ap211unitech** [comment]
Fixed now. Changed to `From other funding account(s)`
