### ISSUE TITLE
suggestion: include trading account name in trading account lists if known to the browser

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#614]
Suggesting to include the name of the trading account if it's known to the browser for these screens. I had to go back and forth to determine which account is which based off just the address.

I understand not all names could be populated if they don't exist in the browser but some can be.

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/825b524d-c0fe-4a79-bc72-7f5a0cb9036c)

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/51a16294-e9ba-47ae-9d63-43a01800a254)

onchainaddress:{esrFTmBAFR1vzbTtqoCbj453geXZAnMLRKRrHorLmxVpsc8UR}

**Comment by ap211unitech** [comment]
Fixed
