### ISSUE TITLE
Thea deposit not appearing in balances after backend update

### ISSUE THREAD

**Issue by nashidahmed** [Polkadex-Substrate/Polkadex-Open-Beta#627]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

I made a USDT deposit on Thea yesterday and today over 18 hours later, the deposit still does not appear in my account. The screenshot below shows my Thea transactions. The latest deposit does not appear in the transactions list but shows up in the recent transactions as can be confirmed from the timestamp.
![Screenshot_20240214-080544](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/37153833/951a89a0-692c-4d52-8231-2ccb8e364029)

The balance is not updated in the orderbook either (I have checked both the orderbook link and the internal orderbook link)

onchainaddress:{esoia6ocj8jC4Wq2mSeiCsXf1Z3eHqx7oHQ8hK8iPgHUYAmeC}

**Comment by nuel77** [comment]
Checking this

**Comment by nuel77** [comment]
Can u confirm if the address shared is the one u used for deposit in assethub as well?
i found a failed transfer from assethub 18 hours ago. linked [here](https://polkadex-parachain.subscan.io/xcm_message/polkadot-cf580c6f6a4ce38898cc21c2884630af3adcb8fc). Can u confirm if this is yours? If so you should still have your balance in assethub.

**Comment by nashidahmed** [comment]
Yes, that is the transaction. Looks like the XCM transfer failed but the transfer from my wallet was successful on asset hub as seen [here](https://assethub-polkadot.subscan.io/extrinsic/5653975-2). You can check the sender and see there is no USDT left in it on asset hub and the first transfer is successful from my wallet. I see the tokens are [here](https://assethub-polkadot.subscan.io/account/13cKp89VtmJboAps452NZLkp49hjFVFUS24D7J9NP6v4gdaN?tab=transfer)

**Comment by Gauthamastro** [comment]
Thanks for catching this issue and Its is resolved now, please check. There was a bug in Thea for propagating the message to mainnet. We have fixed it using two sudo txns, 
1. https://polkadex-parachain.subscan.io/extrinsic/0x8d92cb08eff14b3516ec6232696c2aa50f83a797bd2755ee0485bc83d57d37cb
2. https://polkadex-parachain.subscan.io/extrinsic/0xc1503fa833d19d5d0cbf62a15bff1713c613fec5c27c845a1d83ac799d8f53dc

**Comment by nashidahmed** [comment]
Okay, thanks for your response and prompt action. So I shouldn't face this issue if I deposit again right?
