### ISSUE TITLE
OrderBook Transfer Page - Max button populates wrong value if transferring from funding to "other funding account"

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#643]
See image:

![image](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/c7cb01fa-baf3-41b6-9d68-a4625e629ec6)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by jaymansfield** [comment]
@ap211unitech FYI..

**Comment by ap211unitech** [comment]
This is fixed now. You shouldn't face this issue anymore.
