### ISSUE TITLE
Phrasing Suggestion: Don't have an account yet?

### ISSUE THREAD

**Issue by holdemupholders** [Polkadex-Substrate/Polkadex-Open-Beta#66]
Sign in page says, "Don't you have an account yet?" Sign up.
My suggestion is to change it to "Don't have an account yet?" Sign up.

![Screen Shot 2022-07-04 at 8 42 48 PM](https://user-images.githubusercontent.com/79729027/177233432-ea40838c-aea5-4b8d-9052-af817b0f2676.png)

onchainaddress:{esqm4KnSyebv7Cap4oRm7EHbxSne1c7anLn6tQQSx6zDTyVE7}

**Comment by pavankanteti** [comment]
Not relevant in the new sign up flow. Hence closing.

**Comment by pdexpab** [comment]
@holdemupholders - ACTION NEEDED 

⚠️ If the issues you've logged are tagged as 'Unconfirmed', your on-chain identity has not been set up yet. Please be sure the issues you have raised on GitHub match up to a verified on-chain identity so your issue can be counted in the overall rewards tally for cycle 1 of Polkadex Open Beta testing. 

If you don't have a verified on-chain identity, follow the steps in [this video](https://www.youtube.com/watch?v=lJh4ROo4SiM) as soon as you can. Please drop us a line here or on Discord once you've done so.

For more details, please refer to the latest message in the Open Beta channel on the Polkadex Discord server and points 3.e and 3.f in [the Polkadex Open Beta Terms & Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)
