### ISSUE TITLE
Registered account can't login

### ISSUE THREAD

**Issue by faberkeping** [Polkadex-Substrate/Polkadex-Open-Beta#67]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

I've completed the proxy account registration using my Polkadex main account. The login page has been able to detect my proxy account also, but it kept rejecting my login attempt and stated that my proxy account has not been registered.
![image](https://user-images.githubusercontent.com/92147484/177239203-83f48c52-37ea-4ba8-a3ae-e239426ca77b.png)

onchainaddress:{esrCcLWSGJxPpsqYKZ5jWymaT62Q7rsgmeC2637hBp8DEpioz}

**Comment by pavankanteti** [comment]
Testnet was down during this time.
