### ISSUE TITLE
Login page fails to respond

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#69]
Sometimes Login page doesnt really respond and user has to manually reload the page to process with login request

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

**Comment by pavankanteti** [comment]
Can you reproduce this and record your screen?

**Comment by pavankanteti** [comment]
Closing as the login flow changed with the new implementation.
