### ISSUE TITLE
Product improvement comments: Adding $USD price unit instead of TDOT, TETH

### ISSUE THREAD

**Issue by nlinhmus** [Polkadex-Substrate/Polkadex-Open-Beta#76]
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 
Adding $USD price unit instead of TDOT, TETH… TDOT,TETH price unit is not intuitive and confusing, adding $USD price unit display will be more user friendly!

onchainaddress:{esnKE5QZ29QaYsCRt7GDynx2pGnr6ZpZJmYYroFMZab8g8Xxk}

**Comment by pavankanteti** [comment]
Closing as no plan on implementing this now.
