### ISSUE TITLE
Site elements don't work

### ISSUE THREAD

**Issue by shuterr** [Polkadex-Substrate/Polkadex-Open-Beta#78]
The button does not perform its function - collapse the menu
![Снимок](https://user-images.githubusercontent.com/80340429/177388406-cde6416f-5625-4b86-a26e-6b3b0d00ec80.PNG)
![Снимок](https://user-images.githubusercontent.com/80340429/177389199-06be0804-767c-4f8b-a1a0-44132a3db3f3.PNG)
The search doesn't work! Add to Favorites doesn't work!
onchainaddress:{esmucvcHRGknpRwj4BniPy67f7isrc3TGdHNADDT4ySJG7VfK}

**Comment by pavankanteti** [comment]
closing as duplicate of #12
