### ISSUE TITLE
The entrance to the wallet flies off.

### ISSUE THREAD

**Issue by shuterr** [Polkadex-Substrate/Polkadex-Open-Beta#79]
After the page is reloaded, the login to the wallet crashes.
![Снимок](https://user-images.githubusercontent.com/80340429/177388935-7599b66a-47db-4c4b-881b-34ec1b6a27da.PNG)

onchainaddress:{esmucvcHRGknpRwj4BniPy67f7isrc3TGdHNADDT4ySJG7VfK}

**Comment by shuterr** [comment]
> Can you reproduce this and record your screen?

https://www.youtube.com/watch?v=RKGmmqw7Sys

**Comment by pavankanteti** [comment]
This is already fixed in the new implementation.
