### ISSUE TITLE
Cancel Order Doesn't Refresh The List and Receiving error on 2nd time pressing Cancel

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#82]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description
-Cancel Order Doesn't Refresh The List and Receiving error (Order not found) on 2nd time pressing Cancel

https://user-images.githubusercontent.com/108701680/177428830-29d25ccc-7891-4114-a37f-66a002c36cfa.mp4

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by pavankanteti** [comment]
Realtime updates are added now.
