### ISSUE TITLE
Search in My Wallet-->Tokens is not working

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#88]
Search in My Wallet-->Tokens is not working
onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}
![image](https://user-images.githubusercontent.com/94037805/177556350-96b3fa36-9bdd-4b7d-8a10-0508abffae39.png)

**Comment by pavankanteti** [comment]
closing as duplicate
