### ISSUE TITLE
Sorts are not working in Wallet>Tokens

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#89]
Sorts are not working in 'Tokens' section of My Wallet
onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}

![image](https://user-images.githubusercontent.com/94037805/177556697-eb7bf6a4-320e-49b1-a14b-80956764bc99.png)

**Comment by pavankanteti** [comment]
No sorts in the current implementation. Hence closing.
