### ISSUE TITLE
Error Placing Limit Order When Total Contains a Comma (,) and numbers other than 0 after the comma

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#97]
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description
-Error Placing Limit Order When "Total" Contains a Comma (,) character and numbers other than 0 after the comma...

https://user-images.githubusercontent.com/108701680/177561216-36db04c2-01e6-4bf3-b943-ebeaf383385b.mp4

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by pavankanteti** [comment]
At the moment we configured the max total quantity tradable to be 1000 units. Hence you're seeing this error. Try with a smaller price so that the total is less than a 1000 units.

**Comment by pavankanteti** [comment]
Error occurred because of the limit set for trading. Hence closing.
